\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={House prices: Lasso, XGBoost, and a detailed EDA},
            pdfauthor={Erik Bruin},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{House prices: Lasso, XGBoost, and a detailed EDA}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Erik Bruin}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
    \date{}
    \predate{}\postdate{}
  

\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\#Executive Summary

I started this competition by just focusing on getting a good
understanding of the dataset. The EDA is detailed and many
visualizations are included. This version also includes modeling.

\begin{itemize}
\tightlist
\item
  Lasso regressions performs best with a cross validation RMSE-score of
  0.1121. Given the fact that there is a lot of multicolinearity among
  the variables, this was expected. Lasso does not select a substantial
  number of the available variables in its model, as it is supposed to
  do.
\item
  The XGBoost model also performs very well with a cross validation RMSE
  of 0.1162.
\item
  As those two algorithms are very different, averaging predictions is
  likely to improve the predictions. As the Lasso cross validated RMSE
  is better than XGBoost's CV score, I decided to weight the Lasso
  results double.
\end{itemize}

\#Introduction

Kaggle describes this competition as
\href{https://www.kaggle.com/c/house-prices-advanced-regression-techniques}{follows}:

Ask a home buyer to describe their dream house, and they probably won't
begin with the height of the basement ceiling or the proximity to an
east-west railroad. But this playground competition's dataset proves
that much more influences price negotiations than the number of bedrooms
or a white-picket fence.

With 79 explanatory variables describing (almost) every aspect of
residential homes in Ames, Iowa, this competition challenges you to
predict the final price of each home.

\hypertarget{loading-and-exploring-data}{%
\section{Loading and Exploring Data}\label{loading-and-exploring-data}}

\#\#Loading libraries required and reading the data into R

Loading R packages used besides base R.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(knitr)}
\KeywordTok{library}\NormalTok{(ggplot2)}
\KeywordTok{library}\NormalTok{(plyr)}
\KeywordTok{library}\NormalTok{(dplyr)}
\KeywordTok{library}\NormalTok{(corrplot)}
\KeywordTok{library}\NormalTok{(caret)}
\KeywordTok{library}\NormalTok{(gridExtra)}
\KeywordTok{library}\NormalTok{(scales)}
\KeywordTok{library}\NormalTok{(Rmisc)}
\KeywordTok{library}\NormalTok{(ggrepel)}
\KeywordTok{library}\NormalTok{(randomForest)}
\KeywordTok{library}\NormalTok{(psych)}
\KeywordTok{library}\NormalTok{(xgboost)}
\end{Highlighting}
\end{Shaded}

Below, I am reading the csv's as dataframes into R.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"../input/train.csv"}\NormalTok{, }\DataTypeTok{stringsAsFactors =}\NormalTok{ F)}
\NormalTok{test <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"../input/test.csv"}\NormalTok{, }\DataTypeTok{stringsAsFactors =}\NormalTok{ F)}
\end{Highlighting}
\end{Shaded}

\#\#Data size and structure

The train dataset consist of character and integer variables. Most of
the character variables are actually (ordinal) factors, but I chose to
read them into R as character strings as most of them require cleaning
and/or feature engineering first. In total, there are 81
columns/variables, of which the last one is the response variable
(SalePrice). Below, I am displaying only a glimpse of the variables. All
of them are discussed in more detail throughout the document.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{dim}\NormalTok{(train)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1460   81
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(train[,}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{10}\NormalTok{, }\DecValTok{81}\NormalTok{)]) }\CommentTok{#display first 10 variables and the response variable}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    1460 obs. of  11 variables:
##  $ Id         : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ MSSubClass : int  60 20 60 70 60 50 20 60 50 190 ...
##  $ MSZoning   : chr  "RL" "RL" "RL" "RL" ...
##  $ LotFrontage: int  65 80 68 60 84 85 75 NA 51 50 ...
##  $ LotArea    : int  8450 9600 11250 9550 14260 14115 10084 10382 6120 7420 ...
##  $ Street     : chr  "Pave" "Pave" "Pave" "Pave" ...
##  $ Alley      : chr  NA NA NA NA ...
##  $ LotShape   : chr  "Reg" "Reg" "IR1" "IR1" ...
##  $ LandContour: chr  "Lvl" "Lvl" "Lvl" "Lvl" ...
##  $ Utilities  : chr  "AllPub" "AllPub" "AllPub" "AllPub" ...
##  $ SalePrice  : int  208500 181500 223500 140000 250000 143000 307000 200000 129900 118000 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Getting rid of the IDs but keeping the test IDs in a vector. These are needed to compose the submission file}
\NormalTok{test_labels <-}\StringTok{ }\NormalTok{test}\OperatorTok{$}\NormalTok{Id}
\NormalTok{test}\OperatorTok{$}\NormalTok{Id <-}\StringTok{ }\OtherTok{NULL}
\NormalTok{train}\OperatorTok{$}\NormalTok{Id <-}\StringTok{ }\OtherTok{NULL}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{test}\OperatorTok{$}\NormalTok{SalePrice <-}\StringTok{ }\OtherTok{NA}
\NormalTok{all <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(train, test)}
\KeywordTok{dim}\NormalTok{(all)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919   80
\end{verbatim}

Without the Id's, the dataframe consists of 79 predictors and our
response variable SalePrice.

\#Exploring some of the most important variables

\#\#The response variable; SalePrice

As you can see, the sale prices are right skewed. This was expected as
few people can afford very expensive houses. I will keep this in mind,
and take measures before modeling.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{SalePrice)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{fill=}\StringTok{"blue"}\NormalTok{, }\DataTypeTok{binwidth =} \DecValTok{10000}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_x_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{100000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma)}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##   34900  129975  163000  180921  214000  755000    1459
\end{verbatim}

\#\#The most important numeric predictors

The character variables need some work before I can use them. To get a
feel for the dataset, I decided to first see which numeric variables
have a high correlation with the SalePrice.

\#\#\#Correlations with SalePrice

Altogether, there are 10 numeric variables with a correlation of at
least 0.5 with SalePrice. All those correlations are positive.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{numericVars <-}\StringTok{ }\KeywordTok{which}\NormalTok{(}\KeywordTok{sapply}\NormalTok{(all, is.numeric)) }\CommentTok{#index vector numeric variables}
\NormalTok{numericVarNames <-}\StringTok{ }\KeywordTok{names}\NormalTok{(numericVars) }\CommentTok{#saving names vector for use later on}
\KeywordTok{cat}\NormalTok{(}\StringTok{'There are'}\NormalTok{, }\KeywordTok{length}\NormalTok{(numericVars), }\StringTok{'numeric variables'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## There are 37 numeric variables
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all_numVar <-}\StringTok{ }\NormalTok{all[, numericVars]}
\NormalTok{cor_numVar <-}\StringTok{ }\KeywordTok{cor}\NormalTok{(all_numVar, }\DataTypeTok{use=}\StringTok{"pairwise.complete.obs"}\NormalTok{) }\CommentTok{#correlations of all numeric variables}

\CommentTok{#sort on decreasing correlations with SalePrice}
\NormalTok{cor_sorted <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(}\KeywordTok{sort}\NormalTok{(cor_numVar[,}\StringTok{'SalePrice'}\NormalTok{], }\DataTypeTok{decreasing =} \OtherTok{TRUE}\NormalTok{))}
 \CommentTok{#select only high corelations}
\NormalTok{CorHigh <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{which}\NormalTok{(}\KeywordTok{apply}\NormalTok{(cor_sorted, }\DecValTok{1}\NormalTok{, }\ControlFlowTok{function}\NormalTok{(x) }\KeywordTok{abs}\NormalTok{(x)}\OperatorTok{>}\FloatTok{0.5}\NormalTok{)))}
\NormalTok{cor_numVar <-}\StringTok{ }\NormalTok{cor_numVar[CorHigh, CorHigh]}

\KeywordTok{corrplot.mixed}\NormalTok{(cor_numVar, }\DataTypeTok{tl.col=}\StringTok{"black"}\NormalTok{, }\DataTypeTok{tl.pos =} \StringTok{"lt"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-8-1.pdf}

In the remainder of this section, I will visualize the relation between
SalePrice and the two predictors with the highest correlation with
SalePrice; Overall Quality and the `Above Grade' Living Area (this is
the proportion of the house that is not in a basement;
\href{http://www.gimme-shelter.com/above-grade-50066/}{link}).

It also becomes clear the multicollinearity is an issue. For example:
the correlation between GarageCars and GarageArea is very high (0.89),
and both have similar (high) correlations with SalePrice. The other 6
six variables with a correlation higher than 0.5 with SalePrice are:
-TotalBsmtSF: Total square feet of basement area -1stFlrSF: First Floor
square feet -FullBath: Full bathrooms above grade -TotRmsAbvGrd: Total
rooms above grade (does not include bathrooms) -YearBuilt: Original
construction date -YearRemodAdd: Remodel date (same as construction date
if no remodeling or additions)

\#\#\#Overall Quality

Overall Quality has the highest correlation with SalePrice among the
numeric variables (0.79). It rates the overall material and finish of
the house on a scale from 1 (very poor) to 10 (very excellent).

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{factor}\NormalTok{(OverallQual), }\DataTypeTok{y=}\NormalTok{SalePrice))}\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_boxplot}\NormalTok{(}\DataTypeTok{col=}\StringTok{'blue'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Overall Quality'}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{100000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma)}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-9-1.pdf}

The positive correlation is certainly there indeed, and seems to be a
slightly upward curve. Regarding outliers, I do not see any extreme
values. If there is a candidate to take out as an outlier later on, it
seems to be the expensive house with grade 4.

\#\#\#Above Grade (Ground) Living Area (square feet)

The numeric variable with the second highest correlation with SalesPrice
is the Above Grade Living Area. This make a lot of sense; big houses are
generally more expensive.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{GrLivArea, }\DataTypeTok{y=}\NormalTok{SalePrice))}\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{col=}\StringTok{'blue'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{se=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{color=}\StringTok{"black"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{group=}\DecValTok{1}\NormalTok{)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{100000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_text_repel}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =} \KeywordTok{ifelse}\NormalTok{(all}\OperatorTok{$}\NormalTok{GrLivArea[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice)]}\OperatorTok{>}\DecValTok{4500}\NormalTok{, }\KeywordTok{rownames}\NormalTok{(all), }\StringTok{''}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-10-1.pdf}

Especially the two houses with really big living areas and low
SalePrices seem outliers (houses 524 and 1299, see labels in graph). I
will not take them out yet, as taking outliers can be dangerous. For
instance, a low score on the Overall Quality could explain a low price.
However, as you can see below, these two houses actually also score
maximum points on Overall Quality. Therefore, I will keep houses 1299
and 524 in mind as prime candidates to take out as outliers.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all[}\KeywordTok{c}\NormalTok{(}\DecValTok{524}\NormalTok{, }\DecValTok{1299}\NormalTok{), }\KeywordTok{c}\NormalTok{(}\StringTok{'SalePrice'}\NormalTok{, }\StringTok{'GrLivArea'}\NormalTok{, }\StringTok{'OverallQual'}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      SalePrice GrLivArea OverallQual
## 524     184750      4676          10
## 1299    160000      5642          10
\end{verbatim}

\#Missing data, label encoding, and factorizing variables

\#\#Completeness of the data

First of all, I would like to see which variables contain missing
values.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{NAcol <-}\StringTok{ }\KeywordTok{which}\NormalTok{(}\KeywordTok{colSums}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(all)) }\OperatorTok{>}\StringTok{ }\DecValTok{0}\NormalTok{)}
\KeywordTok{sort}\NormalTok{(}\KeywordTok{colSums}\NormalTok{(}\KeywordTok{sapply}\NormalTok{(all[NAcol], is.na)), }\DataTypeTok{decreasing =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       PoolQC  MiscFeature        Alley        Fence    SalePrice 
##         2909         2814         2721         2348         1459 
##  FireplaceQu  LotFrontage  GarageYrBlt GarageFinish   GarageQual 
##         1420          486          159          159          159 
##   GarageCond   GarageType     BsmtCond BsmtExposure     BsmtQual 
##          159          157           82           82           81 
## BsmtFinType2 BsmtFinType1   MasVnrType   MasVnrArea     MSZoning 
##           80           79           24           23            4 
##    Utilities BsmtFullBath BsmtHalfBath   Functional  Exterior1st 
##            2            2            2            2            1 
##  Exterior2nd   BsmtFinSF1   BsmtFinSF2    BsmtUnfSF  TotalBsmtSF 
##            1            1            1            1            1 
##   Electrical  KitchenQual   GarageCars   GarageArea     SaleType 
##            1            1            1            1            1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cat}\NormalTok{(}\StringTok{'There are'}\NormalTok{, }\KeywordTok{length}\NormalTok{(NAcol), }\StringTok{'columns with missing values'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## There are 35 columns with missing values
\end{verbatim}

Of course, the 1459 NAs in SalePrice match the size of the test set
perfectly. This means that I have to fix NAs in 34 predictor variables.

\#\#Imputing missing data \{.tabset\}

In this section, I am going to fix the 34 predictors that contains
missing values. I will go through them working my way down from most NAs
until I have fixed them all. If I stumble upon a variable that actually
forms a group with other variables, I will also deal with them as a
group. For instance, there are multiple variables that relate to Pool,
Garage, and Basement.

As I want to keep the document as readable as possible, I decided to use
the ``Tabs'' option that knitr provides. You can find a short analysis
for each (group of) variables under each Tab. You don't have to go
through all sections, and can also just have a look at a few tabs. If
you do so, I think that especially the Garage and Basement sections are
worthwhile, as I have been carefull in determing which houses really do
not have a basement or garage.

Besides making sure that the NAs are taken care off, I have also
converted character variables into ordinal integers if there is clear
ordinality, or into factors if levels are categories without ordinality.
I will convert these factors into numeric later on by using one-hot
encoding (using the model.matrix function).

\#\#\#Pool variables

\textbf{Pool Quality and the PoolArea variable}

The PoolQC is the variable with most NAs. The description is as follows:

PoolQC: Pool quality

\begin{verbatim}
   Ex   Excellent
   Gd   Good
   TA   Average/Typical
   Fa   Fair
   NA   No Pool
   
\end{verbatim}

So, it is obvious that I need to just assign `No Pool' to the NAs. Also,
the high number of NAs makes sense as normally only a small proportion
of houses have a pool.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{PoolQC[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{PoolQC)] <-}\StringTok{ 'None'}
\end{Highlighting}
\end{Shaded}

It is also clear that I can label encode this variable as the values are
ordinal. As there a multiple variables that use the same quality levels,
I am going to create a vector that I can reuse later on.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Qualities <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'None'}\NormalTok{ =}\StringTok{ }\DecValTok{0}\NormalTok{, }\StringTok{'Po'}\NormalTok{ =}\StringTok{ }\DecValTok{1}\NormalTok{, }\StringTok{'Fa'}\NormalTok{ =}\StringTok{ }\DecValTok{2}\NormalTok{, }\StringTok{'TA'}\NormalTok{ =}\StringTok{ }\DecValTok{3}\NormalTok{, }\StringTok{'Gd'}\NormalTok{ =}\StringTok{ }\DecValTok{4}\NormalTok{, }\StringTok{'Ex'}\NormalTok{ =}\StringTok{ }\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Now, I can use the function `revalue' to do the work for me.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{PoolQC<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{PoolQC, Qualities))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{PoolQC)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    2    4    5 
## 2909    2    4    4
\end{verbatim}

However, there is a second variable that relates to Pools. This is the
PoolArea variable (in square feet). As you can see below, there are 3
houses without PoolQC. First, I checked if there was a clear relation
between the PoolArea and the PoolQC. As I did not see a clear relation
(bigger of smaller pools with better PoolQC), I am going to impute
PoolQC values based on the Overall Quality of the houses (which is not
very high for those 3 houses).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all[all}\OperatorTok{$}\NormalTok{PoolArea}\OperatorTok{>}\DecValTok{0} \OperatorTok{&}\StringTok{ }\NormalTok{all}\OperatorTok{$}\NormalTok{PoolQC}\OperatorTok{==}\DecValTok{0}\NormalTok{, }\KeywordTok{c}\NormalTok{(}\StringTok{'PoolArea'}\NormalTok{, }\StringTok{'PoolQC'}\NormalTok{, }\StringTok{'OverallQual'}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      PoolArea PoolQC OverallQual
## 2421      368      0           4
## 2504      444      0           6
## 2600      561      0           3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{PoolQC[}\DecValTok{2421}\NormalTok{] <-}\StringTok{ }\DecValTok{2}
\NormalTok{all}\OperatorTok{$}\NormalTok{PoolQC[}\DecValTok{2504}\NormalTok{] <-}\StringTok{ }\DecValTok{3}
\NormalTok{all}\OperatorTok{$}\NormalTok{PoolQC[}\DecValTok{2600}\NormalTok{] <-}\StringTok{ }\DecValTok{2}
\end{Highlighting}
\end{Shaded}

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#\#Miscellaneous Feature

\textbf{Miscellaneous feature not covered in other categories}

Within Miscellaneous Feature, there are 2814 NAs. As the values are not
ordinal, I will convert MiscFeature into a factor. Values:

\begin{verbatim}
   Elev Elevator
   Gar2 2nd Garage (if not described in garage section)
   Othr Other
   Shed Shed (over 100 SF)
   TenC Tennis Court
   NA   None
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{MiscFeature[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{MiscFeature)] <-}\StringTok{ 'None'}
\NormalTok{all}\OperatorTok{$}\NormalTok{MiscFeature <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{MiscFeature)}

\KeywordTok{ggplot}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{MiscFeature, }\DataTypeTok{y=}\NormalTok{SalePrice)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'summary'}\NormalTok{, }\DataTypeTok{fun.y =} \StringTok{"median"}\NormalTok{, }\DataTypeTok{fill=}\StringTok{'blue'}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{100000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_label}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ ..count.., }\DataTypeTok{y =}\NormalTok{ ..count..))}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-17-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{MiscFeature)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Gar2 None Othr Shed TenC 
##    5 2814    4   95    1
\end{verbatim}

When looking at the frequencies, the variable seems irrelevant to me.
Having a shed probably means `no Garage', which would explain the lower
sales price for Shed. Also, while it makes a lot of sense that a house
with a Tennis court is expensive, there is only one house with a tennis
court in the training set.

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#\#Alley

\textbf{Type of alley access to property}

Within Alley, there are 2721 NAs. As the values are not ordinal, I will
convert Alley into a factor. Values:

\begin{verbatim}
   Grvl Gravel
   Pave Paved
   NA   No alley access
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{Alley[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{Alley)] <-}\StringTok{ 'None'}
\NormalTok{all}\OperatorTok{$}\NormalTok{Alley <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{Alley)}

\KeywordTok{ggplot}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{Alley, }\DataTypeTok{y=}\NormalTok{SalePrice)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'summary'}\NormalTok{, }\DataTypeTok{fun.y =} \StringTok{"median"}\NormalTok{, }\DataTypeTok{fill=}\StringTok{'blue'}\NormalTok{)}\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{200000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{50000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma)}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-18-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Alley)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Grvl None Pave 
##  120 2721   78
\end{verbatim}

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#\#Fence

\textbf{Fence quality}

Within Fence, there are 2348 NAs. The values seem to be ordinal. Values:

\begin{verbatim}
   GdPrv    Good Privacy
   MnPrv    Minimum Privacy
   GdWo Good Wood
   MnWw Minimum Wood/Wire
   NA   No Fence
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{Fence[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{Fence)] <-}\StringTok{ 'None'}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Fence)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## GdPrv  GdWo MnPrv  MnWw  None 
##   118   112   329    12  2348
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),] }\OperatorTok{%>%}\StringTok{ }\KeywordTok{group_by}\NormalTok{(Fence) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{median =} \KeywordTok{median}\NormalTok{(SalePrice), }\DataTypeTok{counts=}\KeywordTok{n}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 5 x 3
##   Fence median counts
##   <chr>  <dbl>  <int>
## 1 GdPrv 167500     59
## 2 GdWo  138750     54
## 3 MnPrv 137450    157
## 4 MnWw  130000     11
## 5 None  173000   1179
\end{verbatim}

My conclusion is that the values do not seem ordinal (no fence is best).
Therefore, I will convert Fence into a factor.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{Fence <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{Fence)}
\end{Highlighting}
\end{Shaded}

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#\#Fireplace variables

\textbf{Fireplace quality, and Number of fireplaces}

Within Fireplace Quality, there are 1420 NAs. Number of fireplaces is
complete.

\textbf{Fireplace quality}

The number of NAs in FireplaceQu matches the number of houses with 0
fireplaces. This means that I can safely replace the NAs in FireplaceQu
with `no fireplace'. The values are ordinal, and I can use the Qualities
vector that I have already created for the Pool Quality. Values:

\begin{verbatim}
   Ex   Excellent - Exceptional Masonry Fireplace
   Gd   Good - Masonry Fireplace in main level
   TA   Average - Prefabricated Fireplace in main living area or Masonry Fireplace in basement
   Fa   Fair - Prefabricated Fireplace in basement
   Po   Poor - Ben Franklin Stove
   NA   No Fireplace
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{FireplaceQu[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{FireplaceQu)] <-}\StringTok{ 'None'}
\NormalTok{all}\OperatorTok{$}\NormalTok{FireplaceQu<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{FireplaceQu, Qualities))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{FireplaceQu)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2    3    4    5 
## 1420   46   74  592  744   43
\end{verbatim}

\textbf{Number of fireplaces}

Fireplaces is an integer variable, and there are no missing values.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Fireplaces)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2    3    4 
## 1420 1268  219   11    1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Fireplaces))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#\#Lot variables

3 variables. One with 1 NA, and 2 complete variables.

\textbf{LotFrontage: Linear feet of street connected to property}

486 NAs. The most reasonable imputation seems to take the median per
neigborhood.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{LotFrontage),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(Neighborhood), }\DataTypeTok{y=}\NormalTok{LotFrontage)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'summary'}\NormalTok{, }\DataTypeTok{fun.y =} \StringTok{"median"}\NormalTok{, }\DataTypeTok{fill=}\StringTok{'blue'}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{45}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-23-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(all))\{}
        \ControlFlowTok{if}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{LotFrontage[i]))\{}
\NormalTok{               all}\OperatorTok{$}\NormalTok{LotFrontage[i] <-}\StringTok{ }\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{median}\NormalTok{(all}\OperatorTok{$}\NormalTok{LotFrontage[all}\OperatorTok{$}\NormalTok{Neighborhood}\OperatorTok{==}\NormalTok{all}\OperatorTok{$}\NormalTok{Neighborhood[i]], }\DataTypeTok{na.rm=}\OtherTok{TRUE}\NormalTok{)) }
\NormalTok{        \}}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\textbf{LotShape: General shape of property}

No NAs. Values seem ordinal (Regular=best)

\begin{verbatim}
   Reg  Regular 
   IR1  Slightly irregular
   IR2  Moderately Irregular
   IR3  Irregular
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{LotShape<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{LotShape, }\KeywordTok{c}\NormalTok{(}\StringTok{'IR3'}\NormalTok{=}\DecValTok{0}\NormalTok{, }\StringTok{'IR2'}\NormalTok{=}\DecValTok{1}\NormalTok{, }\StringTok{'IR1'}\NormalTok{=}\DecValTok{2}\NormalTok{, }\StringTok{'Reg'}\NormalTok{=}\DecValTok{3}\NormalTok{)))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{LotShape)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2    3 
##   16   76  968 1859
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{LotShape))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{LotConfig: Lot configuration}

No NAs. The values seemed possibly ordinal to me, but the visualization
does not show this. Therefore, I will convert the variable into a
factor.

\begin{verbatim}
   Inside   Inside lot
   Corner   Corner lot
   CulDSac  Cul-de-sac
   FR2  Frontage on 2 sides of property
   FR3  Frontage on 3 sides of property
   
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(LotConfig), }\DataTypeTok{y=}\NormalTok{SalePrice)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'summary'}\NormalTok{, }\DataTypeTok{fun.y =} \StringTok{"median"}\NormalTok{, }\DataTypeTok{fill=}\StringTok{'blue'}\NormalTok{)}\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{100000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_label}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ ..count.., }\DataTypeTok{y =}\NormalTok{ ..count..))}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-26-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{LotConfig <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{LotConfig)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{LotConfig)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Corner CulDSac     FR2     FR3  Inside 
##     511     176      85      14    2133
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{LotConfig))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#\#Garage variables

\textbf{Altogether, there are 7 variables related to garages}

Two of those have one NA (GarageCars and GarageArea), one has 157 NAs
(GarageType), 4 variables have 159 NAs.

First of all, I am going to replace all 159 missing \textbf{GarageYrBlt:
Year garage was built} values with the values in YearBuilt (this is
similar to YearRemodAdd, which also defaults to YearBuilt if no
remodeling or additions).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{GarageYrBlt[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageYrBlt)] <-}\StringTok{ }\NormalTok{all}\OperatorTok{$}\NormalTok{YearBuilt[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageYrBlt)]}
\end{Highlighting}
\end{Shaded}

As NAs mean `No Garage' for character variables, I now want to find out
where the differences between the 157 NA GarageType and the other 3
character variables with 159 NAs come from.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#check if all 157 NAs are the same observations among the variables with 157/159 NAs}
\KeywordTok{length}\NormalTok{(}\KeywordTok{which}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageType) }\OperatorTok{&}\StringTok{ }\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageFinish) }\OperatorTok{&}\StringTok{ }\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageCond) }\OperatorTok{&}\StringTok{ }\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageQual)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 157
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Find the 2 additional NAs}
\KeywordTok{kable}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageType) }\OperatorTok{&}\StringTok{ }\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageFinish), }\KeywordTok{c}\NormalTok{(}\StringTok{'GarageCars'}\NormalTok{, }\StringTok{'GarageArea'}\NormalTok{, }\StringTok{'GarageType'}\NormalTok{, }\StringTok{'GarageCond'}\NormalTok{, }\StringTok{'GarageQual'}\NormalTok{, }\StringTok{'GarageFinish'}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrllll@{}}
\toprule
& GarageCars & GarageArea & GarageType & GarageCond & GarageQual &
GarageFinish\tabularnewline
\midrule
\endhead
2127 & 1 & 360 & Detchd & NA & NA & NA\tabularnewline
2577 & NA & NA & Detchd & NA & NA & NA\tabularnewline
\bottomrule
\end{longtable}

The 157 NAs within GarageType all turn out to be NA in GarageCondition,
GarageQuality, and GarageFinish as well. The differences are found in
houses 2127 and 2577. As you can see, house 2127 actually does seem to
have a Garage and house 2577 does not. Therefore, there should be 158
houses without a Garage. To fix house 2127, I will imputate the most
common values (modes) for GarageCond, GarageQual, and GarageFinish.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Imputing modes.}
\NormalTok{all}\OperatorTok{$}\NormalTok{GarageCond[}\DecValTok{2127}\NormalTok{] <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\OperatorTok{-}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageCond)))[}\DecValTok{1}\NormalTok{]}
\NormalTok{all}\OperatorTok{$}\NormalTok{GarageQual[}\DecValTok{2127}\NormalTok{] <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\OperatorTok{-}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageQual)))[}\DecValTok{1}\NormalTok{]}
\NormalTok{all}\OperatorTok{$}\NormalTok{GarageFinish[}\DecValTok{2127}\NormalTok{] <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\OperatorTok{-}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageFinish)))[}\DecValTok{1}\NormalTok{]}

\CommentTok{#display "fixed" house}
\KeywordTok{kable}\NormalTok{(all[}\DecValTok{2127}\NormalTok{, }\KeywordTok{c}\NormalTok{(}\StringTok{'GarageYrBlt'}\NormalTok{, }\StringTok{'GarageCars'}\NormalTok{, }\StringTok{'GarageArea'}\NormalTok{, }\StringTok{'GarageType'}\NormalTok{, }\StringTok{'GarageCond'}\NormalTok{, }\StringTok{'GarageQual'}\NormalTok{, }\StringTok{'GarageFinish'}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrrllll@{}}
\toprule
& GarageYrBlt & GarageCars & GarageArea & GarageType & GarageCond &
GarageQual & GarageFinish\tabularnewline
\midrule
\endhead
2127 & 1910 & 1 & 360 & Detchd & TA & TA & Unf\tabularnewline
\bottomrule
\end{longtable}

\textbf{GarageCars and GarageArea: Size of garage in car capacity and
Size of garage in square}

Both have 1 NA. As you can see above, it is house 2577 for both
variables. The problem probably occured as the GarageType for this house
is ``detached'', while all other Garage-variables seem to indicate that
this house has no Garage.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#fixing 3 values for house 2577}
\NormalTok{all}\OperatorTok{$}\NormalTok{GarageCars[}\DecValTok{2577}\NormalTok{] <-}\StringTok{ }\DecValTok{0}
\NormalTok{all}\OperatorTok{$}\NormalTok{GarageArea[}\DecValTok{2577}\NormalTok{] <-}\StringTok{ }\DecValTok{0}
\NormalTok{all}\OperatorTok{$}\NormalTok{GarageType[}\DecValTok{2577}\NormalTok{] <-}\StringTok{ }\OtherTok{NA}

\CommentTok{#check if NAs of the character variables are now all 158}
\KeywordTok{length}\NormalTok{(}\KeywordTok{which}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageType) }\OperatorTok{&}\StringTok{ }\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageFinish) }\OperatorTok{&}\StringTok{ }\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageCond) }\OperatorTok{&}\StringTok{ }\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageQual)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 158
\end{verbatim}

Now, the 4 character variables related to garage all have the same set
of 158 NAs, which correspond to `No Garage'. I will fix all of them in
the remainder of this section

\textbf{GarageType: Garage location}

The values do not seem ordinal, so I will convert into a factor.

\begin{verbatim}
   2Types   More than one type of garage
   Attchd   Attached to home
   Basment  Basement Garage
   BuiltIn  Built-In (Garage part of house - typically has room above garage)
   CarPort  Car Port
   Detchd   Detached from home
   NA   No Garage
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{GarageType[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageType)] <-}\StringTok{ 'No Garage'}
\NormalTok{all}\OperatorTok{$}\NormalTok{GarageType <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageType)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageType)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    2Types    Attchd   Basment   BuiltIn   CarPort    Detchd No Garage 
##        23      1723        36       186        15       778       158
\end{verbatim}

\textbf{GarageFinish: Interior finish of the garage}

The values are ordinal.

\begin{verbatim}
   Fin  Finished
   RFn  Rough Finished  
   Unf  Unfinished
   NA   No Garage       
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{GarageFinish[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageFinish)] <-}\StringTok{ 'None'}
\NormalTok{Finish <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'None'}\NormalTok{=}\DecValTok{0}\NormalTok{, }\StringTok{'Unf'}\NormalTok{=}\DecValTok{1}\NormalTok{, }\StringTok{'RFn'}\NormalTok{=}\DecValTok{2}\NormalTok{, }\StringTok{'Fin'}\NormalTok{=}\DecValTok{3}\NormalTok{)}

\NormalTok{all}\OperatorTok{$}\NormalTok{GarageFinish<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageFinish, Finish))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageFinish)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2    3 
##  158 1231  811  719
\end{verbatim}

\textbf{GarageQual: Garage quality}

Another variable than can be made ordinal with the Qualities vector.

\begin{verbatim}
   Ex   Excellent
   Gd   Good
   TA   Typical/Average
   Fa   Fair
   Po   Poor
   NA   No Garage
   
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{GarageQual[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageQual)] <-}\StringTok{ 'None'}
\NormalTok{all}\OperatorTok{$}\NormalTok{GarageQual<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageQual, Qualities))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageQual)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2    3    4    5 
##  158    5  124 2605   24    3
\end{verbatim}

\textbf{GarageCond: Garage condition}

Another variable than can be made ordinal with the Qualities vector.

\begin{verbatim}
   Ex   Excellent
   Gd   Good
   TA   Typical/Average
   Fa   Fair
   Po   Poor
   NA   No Garage
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{GarageCond[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageCond)] <-}\StringTok{ 'None'}
\NormalTok{all}\OperatorTok{$}\NormalTok{GarageCond<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageCond, Qualities))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{GarageCond)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2    3    4    5 
##  158   14   74 2655   15    3
\end{verbatim}

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#\#Basement Variables

\textbf{Altogether, there are 11 variables that relate to the Basement
of a house}

Five of those have 79-82 NAs, six have one or two NAs.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#check if all 79 NAs are the same observations among the variables with 80+ NAs}
\KeywordTok{length}\NormalTok{(}\KeywordTok{which}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtQual) }\OperatorTok{&}\StringTok{ }\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtCond) }\OperatorTok{&}\StringTok{ }\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtExposure) }\OperatorTok{&}\StringTok{ }\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFinType1) }\OperatorTok{&}\StringTok{ }\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFinType2)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 79
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Find the additional NAs; BsmtFinType1 is the one with 79 NAs}
\NormalTok{all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFinType1) }\OperatorTok{&}\StringTok{ }\NormalTok{(}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtCond)}\OperatorTok{|}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtQual)}\OperatorTok{|}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtExposure)}\OperatorTok{|}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFinType2)), }\KeywordTok{c}\NormalTok{(}\StringTok{'BsmtQual'}\NormalTok{, }\StringTok{'BsmtCond'}\NormalTok{, }\StringTok{'BsmtExposure'}\NormalTok{, }\StringTok{'BsmtFinType1'}\NormalTok{, }\StringTok{'BsmtFinType2'}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      BsmtQual BsmtCond BsmtExposure BsmtFinType1 BsmtFinType2
## 333        Gd       TA           No          GLQ         <NA>
## 949        Gd       TA         <NA>          Unf          Unf
## 1488       Gd       TA         <NA>          Unf          Unf
## 2041       Gd     <NA>           Mn          GLQ          Rec
## 2186       TA     <NA>           No          BLQ          Unf
## 2218     <NA>       Fa           No          Unf          Unf
## 2219     <NA>       TA           No          Unf          Unf
## 2349       Gd       TA         <NA>          Unf          Unf
## 2525       TA     <NA>           Av          ALQ          Unf
\end{verbatim}

So altogether, it seems as if there are 79 houses without a basement,
because the basement variables of the other houses with missing values
are all 80\% complete (missing 1 out of 5 values). I am going to impute
the modes to fix those 9 houses.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Imputing modes.}
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtFinType2[}\DecValTok{333}\NormalTok{] <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\OperatorTok{-}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFinType2)))[}\DecValTok{1}\NormalTok{]}
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtExposure[}\KeywordTok{c}\NormalTok{(}\DecValTok{949}\NormalTok{, }\DecValTok{1488}\NormalTok{, }\DecValTok{2349}\NormalTok{)] <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\OperatorTok{-}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtExposure)))[}\DecValTok{1}\NormalTok{]}
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtCond[}\KeywordTok{c}\NormalTok{(}\DecValTok{2041}\NormalTok{, }\DecValTok{2186}\NormalTok{, }\DecValTok{2525}\NormalTok{)] <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\OperatorTok{-}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtCond)))[}\DecValTok{1}\NormalTok{]}
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtQual[}\KeywordTok{c}\NormalTok{(}\DecValTok{2218}\NormalTok{, }\DecValTok{2219}\NormalTok{)] <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\OperatorTok{-}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtQual)))[}\DecValTok{1}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

Now that the 5 variables considered agree upon 79 houses with `no
basement', I am going to factorize/hot encode them below.

\textbf{BsmtQual: Evaluates the height of the basement}

A variable than can be made ordinal with the Qualities vector.

\begin{verbatim}
   Ex   Excellent (100+ inches) 
   Gd   Good (90-99 inches)
   TA   Typical (80-89 inches)
   Fa   Fair (70-79 inches)
   Po   Poor (<70 inches
   NA   No Basement
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtQual[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtQual)] <-}\StringTok{ 'None'}
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtQual<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtQual, Qualities))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtQual)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    2    3    4    5 
##   79   88 1285 1209  258
\end{verbatim}

\textbf{BsmtCond: Evaluates the general condition of the basement}

A variable than can be made ordinal with the Qualities vector.

\begin{verbatim}
   Ex   Excellent
   Gd   Good
   TA   Typical - slight dampness allowed
   Fa   Fair - dampness or some cracking or settling
   Po   Poor - Severe cracking, settling, or wetness
   NA   No Basement
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtCond[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtCond)] <-}\StringTok{ 'None'}
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtCond<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtCond, Qualities))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtCond)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2    3    4 
##   79    5  104 2609  122
\end{verbatim}

\textbf{BsmtExposure: Refers to walkout or garden level walls}

A variable than can be made ordinal.

\begin{verbatim}
   Gd   Good Exposure
   Av   Average Exposure (split levels or foyers typically score average or above)  
   Mn   Mimimum Exposure
   No   No Exposure
   NA   No Basement
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtExposure[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtExposure)] <-}\StringTok{ 'None'}
\NormalTok{Exposure <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'None'}\NormalTok{=}\DecValTok{0}\NormalTok{, }\StringTok{'No'}\NormalTok{=}\DecValTok{1}\NormalTok{, }\StringTok{'Mn'}\NormalTok{=}\DecValTok{2}\NormalTok{, }\StringTok{'Av'}\NormalTok{=}\DecValTok{3}\NormalTok{, }\StringTok{'Gd'}\NormalTok{=}\DecValTok{4}\NormalTok{)}

\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtExposure<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtExposure, Exposure))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtExposure)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2    3    4 
##   79 1907  239  418  276
\end{verbatim}

\textbf{BsmtFinType1: Rating of basement finished area}

A variable than can be made ordinal.

\begin{verbatim}
   GLQ  Good Living Quarters
   ALQ  Average Living Quarters
   BLQ  Below Average Living Quarters   
   Rec  Average Rec Room
   LwQ  Low Quality
   Unf  Unfinshed
   NA   No Basement
    
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtFinType1[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFinType1)] <-}\StringTok{ 'None'}
\NormalTok{FinType <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'None'}\NormalTok{=}\DecValTok{0}\NormalTok{, }\StringTok{'Unf'}\NormalTok{=}\DecValTok{1}\NormalTok{, }\StringTok{'LwQ'}\NormalTok{=}\DecValTok{2}\NormalTok{, }\StringTok{'Rec'}\NormalTok{=}\DecValTok{3}\NormalTok{, }\StringTok{'BLQ'}\NormalTok{=}\DecValTok{4}\NormalTok{, }\StringTok{'ALQ'}\NormalTok{=}\DecValTok{5}\NormalTok{, }\StringTok{'GLQ'}\NormalTok{=}\DecValTok{6}\NormalTok{)}

\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtFinType1<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFinType1, FinType))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFinType1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   0   1   2   3   4   5   6 
##  79 851 154 288 269 429 849
\end{verbatim}

\textbf{BsmtFinType2: Rating of basement finished area (if multiple
types)}

A variable than can be made ordinal with the FinType vector.

\begin{verbatim}
   GLQ  Good Living Quarters
   ALQ  Average Living Quarters
   BLQ  Below Average Living Quarters   
   Rec  Average Rec Room
   LwQ  Low Quality
   Unf  Unfinshed
   NA   No Basement
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtFinType2[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFinType2)] <-}\StringTok{ 'None'}
\NormalTok{FinType <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'None'}\NormalTok{=}\DecValTok{0}\NormalTok{, }\StringTok{'Unf'}\NormalTok{=}\DecValTok{1}\NormalTok{, }\StringTok{'LwQ'}\NormalTok{=}\DecValTok{2}\NormalTok{, }\StringTok{'Rec'}\NormalTok{=}\DecValTok{3}\NormalTok{, }\StringTok{'BLQ'}\NormalTok{=}\DecValTok{4}\NormalTok{, }\StringTok{'ALQ'}\NormalTok{=}\DecValTok{5}\NormalTok{, }\StringTok{'GLQ'}\NormalTok{=}\DecValTok{6}\NormalTok{)}

\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtFinType2<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFinType2, FinType))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFinType2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2    3    4    5    6 
##   79 2494   87  105   68   52   34
\end{verbatim}

\textbf{Remaining Basement variabes with just a few NAs}

I now still have to deal with those 6 variables that have 1 or 2 NAs.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#display remaining NAs. Using BsmtQual as a reference for the 79 houses without basement agreed upon earlier}
\NormalTok{all[(}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFullBath)}\OperatorTok{|}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtHalfBath)}\OperatorTok{|}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFinSF1)}\OperatorTok{|}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFinSF2)}\OperatorTok{|}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtUnfSF)}\OperatorTok{|}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{TotalBsmtSF)), }\KeywordTok{c}\NormalTok{(}\StringTok{'BsmtQual'}\NormalTok{, }\StringTok{'BsmtFullBath'}\NormalTok{, }\StringTok{'BsmtHalfBath'}\NormalTok{, }\StringTok{'BsmtFinSF1'}\NormalTok{, }\StringTok{'BsmtFinSF2'}\NormalTok{, }\StringTok{'BsmtUnfSF'}\NormalTok{, }\StringTok{'TotalBsmtSF'}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      BsmtQual BsmtFullBath BsmtHalfBath BsmtFinSF1 BsmtFinSF2 BsmtUnfSF
## 2121        0           NA           NA         NA         NA        NA
## 2189        0           NA           NA          0          0         0
##      TotalBsmtSF
## 2121          NA
## 2189           0
\end{verbatim}

It should be obvious that those remaining NAs all refer to `not
present'. Below, I am fixing those remaining variables.

\textbf{BsmtFullBath: Basement full bathrooms}

An integer variable.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtFullBath[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFullBath)] <-}\DecValTok{0}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFullBath)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2    3 
## 1707 1172   38    2
\end{verbatim}

\textbf{BsmtHalfBath: Basement half bathrooms}

An integer variable.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtHalfBath[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtHalfBath)] <-}\DecValTok{0}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtHalfBath)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2 
## 2744  171    4
\end{verbatim}

\textbf{BsmtFinSF1: Type 1 finished square feet}

An integer variable.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtFinSF1[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFinSF1)] <-}\DecValTok{0}
\end{Highlighting}
\end{Shaded}

\textbf{BsmtFinSF2: Type 2 finished square feet}

An integer variable.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtFinSF2[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtFinSF2)] <-}\DecValTok{0}
\end{Highlighting}
\end{Shaded}

\textbf{BsmtUnfSF: Unfinished square feet of basement area}

An integer variable.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtUnfSF[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtUnfSF)] <-}\DecValTok{0}
\end{Highlighting}
\end{Shaded}

\textbf{TotalBsmtSF: Total square feet of basement area}

An integer variable.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{TotalBsmtSF[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{TotalBsmtSF)] <-}\DecValTok{0}
\end{Highlighting}
\end{Shaded}

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#\#Masonry variables

\textbf{Masonry veneer type, and masonry veneer area}

Masonry veneer type has 24 NAs. Masonry veneer area has 23 NAs. If a
house has a veneer area, it should also have a masonry veneer type.
Let's fix this one first.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#check if the 23 houses with veneer area NA are also NA in the veneer type}
\KeywordTok{length}\NormalTok{(}\KeywordTok{which}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{MasVnrType) }\OperatorTok{&}\StringTok{ }\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{MasVnrArea)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 23
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#find the one that should have a MasVnrType}
\NormalTok{all[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{MasVnrType) }\OperatorTok{&}\StringTok{ }\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{MasVnrArea), }\KeywordTok{c}\NormalTok{(}\StringTok{'MasVnrType'}\NormalTok{, }\StringTok{'MasVnrArea'}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      MasVnrType MasVnrArea
## 2611       <NA>        198
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#fix this veneer type by imputing the mode}
\NormalTok{all}\OperatorTok{$}\NormalTok{MasVnrType[}\DecValTok{2611}\NormalTok{] <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\OperatorTok{-}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{MasVnrType)))[}\DecValTok{2}\NormalTok{] }\CommentTok{#taking the 2nd value as the 1st is 'none'}
\NormalTok{all[}\DecValTok{2611}\NormalTok{, }\KeywordTok{c}\NormalTok{(}\StringTok{'MasVnrType'}\NormalTok{, }\StringTok{'MasVnrArea'}\NormalTok{)]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      MasVnrType MasVnrArea
## 2611    BrkFace        198
\end{verbatim}

This leaves me with 23 houses that really have no masonry.

\textbf{Masonry veneer type}

Will check the ordinality below.

\begin{verbatim}
   BrkCmn   Brick Common
   BrkFace  Brick Face
   CBlock   Cinder Block
   None None
   Stone    Stone
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{MasVnrType[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{MasVnrType)] <-}\StringTok{ 'None'}

\NormalTok{all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),] }\OperatorTok{%>%}\StringTok{ }\KeywordTok{group_by}\NormalTok{(MasVnrType) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{median =} \KeywordTok{median}\NormalTok{(SalePrice), }\DataTypeTok{counts=}\KeywordTok{n}\NormalTok{()) }\OperatorTok{%>%}\StringTok{ }\KeywordTok{arrange}\NormalTok{(median)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 3
##   MasVnrType median counts
##   <chr>       <dbl>  <int>
## 1 BrkCmn     139000     15
## 2 None       143125    872
## 3 BrkFace    181000    445
## 4 Stone      246839    128
\end{verbatim}

There seems to be a significant difference between ``common brick/none''
and the other types. I assume that simple stones and for instance wooden
houses are just cheaper. I will make the ordinality accordingly.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Masonry <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'None'}\NormalTok{=}\DecValTok{0}\NormalTok{, }\StringTok{'BrkCmn'}\NormalTok{=}\DecValTok{0}\NormalTok{, }\StringTok{'BrkFace'}\NormalTok{=}\DecValTok{1}\NormalTok{, }\StringTok{'Stone'}\NormalTok{=}\DecValTok{2}\NormalTok{)}
\NormalTok{all}\OperatorTok{$}\NormalTok{MasVnrType<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{MasVnrType, Masonry))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{MasVnrType)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2 
## 1790  880  249
\end{verbatim}

\textbf{MasVnrArea: Masonry veneer area in square feet}

An integer variable.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{MasVnrArea[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{MasVnrArea)] <-}\DecValTok{0}
\end{Highlighting}
\end{Shaded}

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#\#MS Zoning

\textbf{MSZoning: Identifies the general zoning classification of the
sale}

4 NAs. Values are categorical.

\begin{verbatim}
   A    Agriculture
   C    Commercial
   FV   Floating Village Residential
   I    Industrial
   RH   Residential High Density
   RL   Residential Low Density
   RP   Residential Low Density Park 
   RM   Residential Medium Density
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#imputing the mode}
\NormalTok{all}\OperatorTok{$}\NormalTok{MSZoning[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{MSZoning)] <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\OperatorTok{-}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{MSZoning)))[}\DecValTok{1}\NormalTok{]}
\NormalTok{all}\OperatorTok{$}\NormalTok{MSZoning <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{MSZoning)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{MSZoning)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## C (all)      FV      RH      RL      RM 
##      25     139      26    2269     460
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{MSZoning))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#\#Kitchen variables

\textbf{Kitchen quality and numer of Kitchens above grade}

Kitchen quality has 1 NA. Number of Kitchens is complete.

\textbf{Kitchen quality}

1NA. Can be made ordinal with the qualities vector.

\begin{verbatim}
   Ex   Excellent
   Gd   Good
   TA   Typical/Average
   Fa   Fair
   Po   Poor
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{KitchenQual[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{KitchenQual)] <-}\StringTok{ 'TA'} \CommentTok{#replace with most common value}
\NormalTok{all}\OperatorTok{$}\NormalTok{KitchenQual<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{KitchenQual, Qualities))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{KitchenQual)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    2    3    4    5 
##   70 1493 1151  205
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{KitchenQual))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Number of Kitchens above grade}

An integer variable with no NAs.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{KitchenAbvGr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2    3 
##    3 2785  129    2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{KitchenAbvGr))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#\#Utilities

\textbf{Utilities: Type of utilities available}

2 NAs. Ordinal as additional utilities is better.

\begin{verbatim}
   AllPub   All public Utilities (E,G,W,& S)    
   NoSewr   Electricity, Gas, and Water (Septic Tank)
   NoSeWa   Electricity and Gas Only
   ELO  Electricity only
\end{verbatim}

However, the table below shows that only one house does not have all
public utilities. This house is in the train set. Therefore, imputing
`AllPub' for the NAs means that all houses in the test set will have
`AllPub'. This makes the variable useless for prediction. Consequently,
I will get rid of it.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Utilities)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## AllPub NoSeWa 
##   2916      1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{kable}\NormalTok{(all[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{Utilities) }\OperatorTok{|}\StringTok{ }\NormalTok{all}\OperatorTok{$}\NormalTok{Utilities}\OperatorTok{==}\StringTok{'NoSeWa'}\NormalTok{, }\DecValTok{1}\OperatorTok{:}\DecValTok{9}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrlrrllrll@{}}
\toprule
& MSSubClass & MSZoning & LotFrontage & LotArea & Street & Alley &
LotShape & LandContour & Utilities\tabularnewline
\midrule
\endhead
945 & 20 & RL & 82 & 14375 & Pave & None & 2 & Lvl &
NoSeWa\tabularnewline
1916 & 30 & RL & 109 & 21780 & Grvl & None & 3 & Lvl & NA\tabularnewline
1946 & 20 & RL & 64 & 31220 & Pave & None & 2 & Bnk & NA\tabularnewline
\bottomrule
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{Utilities <-}\StringTok{ }\OtherTok{NULL}
\end{Highlighting}
\end{Shaded}

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#\#Home functionality

\textbf{Functional: Home functionality}

1NA. Can be made ordinal (salvage only is worst, typical is best).

\begin{verbatim}
   Typ  Typical Functionality
   Min1 Minor Deductions 1
   Min2 Minor Deductions 2
   Mod  Moderate Deductions
   Maj1 Major Deductions 1
   Maj2 Major Deductions 2
   Sev  Severely Damaged
   Sal  Salvage only
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#impute mode for the 1 NA}
\NormalTok{all}\OperatorTok{$}\NormalTok{Functional[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{Functional)] <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\OperatorTok{-}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Functional)))[}\DecValTok{1}\NormalTok{]}

\NormalTok{all}\OperatorTok{$}\NormalTok{Functional <-}\StringTok{ }\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{Functional, }\KeywordTok{c}\NormalTok{(}\StringTok{'Sal'}\NormalTok{=}\DecValTok{0}\NormalTok{, }\StringTok{'Sev'}\NormalTok{=}\DecValTok{1}\NormalTok{, }\StringTok{'Maj2'}\NormalTok{=}\DecValTok{2}\NormalTok{, }\StringTok{'Maj1'}\NormalTok{=}\DecValTok{3}\NormalTok{, }\StringTok{'Mod'}\NormalTok{=}\DecValTok{4}\NormalTok{, }\StringTok{'Min2'}\NormalTok{=}\DecValTok{5}\NormalTok{, }\StringTok{'Min1'}\NormalTok{=}\DecValTok{6}\NormalTok{, }\StringTok{'Typ'}\NormalTok{=}\DecValTok{7}\NormalTok{)))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Functional)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    1    2    3    4    5    6    7 
##    2    9   19   35   70   65 2719
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Functional))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#\#Exterior variables

\textbf{There are 4 exterior variables}

2 variables have 1 NA, 2 variables have no NAs.

\textbf{Exterior1st: Exterior covering on house}

1 NA. Values are categorical.

\begin{verbatim}
   AsbShng  Asbestos Shingles
   AsphShn  Asphalt Shingles
   BrkComm  Brick Common
   BrkFace  Brick Face
   CBlock   Cinder Block
   CemntBd  Cement Board
   HdBoard  Hard Board
   ImStucc  Imitation Stucco
   MetalSd  Metal Siding
   Other    Other
   Plywood  Plywood
   PreCast  PreCast 
   Stone    Stone
   Stucco   Stucco
   VinylSd  Vinyl Siding
   Wd Sdng  Wood Siding
   WdShing  Wood Shingles
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#imputing mode}
\NormalTok{all}\OperatorTok{$}\NormalTok{Exterior1st[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{Exterior1st)] <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\OperatorTok{-}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Exterior1st)))[}\DecValTok{1}\NormalTok{]}

\NormalTok{all}\OperatorTok{$}\NormalTok{Exterior1st <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{Exterior1st)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Exterior1st)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## AsbShng AsphShn BrkComm BrkFace  CBlock CemntBd HdBoard ImStucc MetalSd 
##      44       2       6      87       2     126     442       1     450 
## Plywood   Stone  Stucco VinylSd Wd Sdng WdShing 
##     221       2      43    1026     411      56
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Exterior1st))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Exterior2nd: Exterior covering on house (if more than one
material)}

1 NA. Values are categorical.

\begin{verbatim}
   AsbShng  Asbestos Shingles
   AsphShn  Asphalt Shingles
   BrkComm  Brick Common
   BrkFace  Brick Face
   CBlock   Cinder Block
   CemntBd  Cement Board
   HdBoard  Hard Board
   ImStucc  Imitation Stucco
   MetalSd  Metal Siding
   Other    Other
   Plywood  Plywood
   PreCast  PreCast
   Stone    Stone
   Stucco   Stucco
   VinylSd  Vinyl Siding
   Wd Sdng  Wood Siding
   WdShing  Wood Shingles
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#imputing mode}
\NormalTok{all}\OperatorTok{$}\NormalTok{Exterior2nd[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{Exterior2nd)] <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\OperatorTok{-}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Exterior2nd)))[}\DecValTok{1}\NormalTok{]}

\NormalTok{all}\OperatorTok{$}\NormalTok{Exterior2nd <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{Exterior2nd)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Exterior2nd)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## AsbShng AsphShn Brk Cmn BrkFace  CBlock CmentBd HdBoard ImStucc MetalSd 
##      38       4      22      47       3     126     406      15     447 
##   Other Plywood   Stone  Stucco VinylSd Wd Sdng Wd Shng 
##       1     270       6      47    1015     391      81
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Exterior2nd))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{ExterQual: Evaluates the quality of the material on the
exterior}

No NAs. Can be made ordinal using the Qualities vector.

\begin{verbatim}
   Ex   Excellent
   Gd   Good
   TA   Average/Typical
   Fa   Fair
   Po   Poor
   
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{ExterQual<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{ExterQual, Qualities))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## The following `from` values were not present in `x`: None, Po
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{ExterQual)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    2    3    4    5 
##   35 1798  979  107
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{ExterQual))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{ExterCond: Evaluates the present condition of the material on
the exterior}

No NAs. Can be made ordinal using the Qualities vector.

\begin{verbatim}
   Ex   Excellent
   Gd   Good
   TA   Average/Typical
   Fa   Fair
   Po   Poor
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{ExterCond<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{ExterCond, Qualities))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## The following `from` values were not present in `x`: None
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{ExterCond)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    1    2    3    4    5 
##    3   67 2538  299   12
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{ExterCond))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#\#Electrical system

\textbf{Electrical: Electrical system}

1 NA. Values are categorical.

\begin{verbatim}
   SBrkr    Standard Circuit Breakers & Romex
   FuseA    Fuse Box over 60 AMP and all Romex wiring (Average) 
   FuseF    60 AMP Fuse Box and mostly Romex wiring (Fair)
   FuseP    60 AMP Fuse Box and mostly knob & tube wiring (poor)
   Mix  Mixed
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#imputing mode}
\NormalTok{all}\OperatorTok{$}\NormalTok{Electrical[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{Electrical)] <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\OperatorTok{-}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Electrical)))[}\DecValTok{1}\NormalTok{]}

\NormalTok{all}\OperatorTok{$}\NormalTok{Electrical <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{Electrical)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Electrical)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## FuseA FuseF FuseP   Mix SBrkr 
##   188    50     8     1  2672
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Electrical))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#\#Sale Type and Condition

\textbf{SaleType: Type of sale}

1 NA. Values are categorical.

\begin{verbatim}
   WD   Warranty Deed - Conventional
   CWD  Warranty Deed - Cash
   VWD  Warranty Deed - VA Loan
   New  Home just constructed and sold
   COD  Court Officer Deed/Estate
   Con  Contract 15% Down payment regular terms
   ConLw    Contract Low Down payment and low interest
   ConLI    Contract Low Interest
   ConLD    Contract Low Down
   Oth  Other
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#imputing mode}
\NormalTok{all}\OperatorTok{$}\NormalTok{SaleType[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SaleType)] <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\OperatorTok{-}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{SaleType)))[}\DecValTok{1}\NormalTok{]}

\NormalTok{all}\OperatorTok{$}\NormalTok{SaleType <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{SaleType)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{SaleType)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   COD   Con ConLD ConLI ConLw   CWD   New   Oth    WD 
##    87     5    26     9     8    12   239     7  2526
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{SaleType))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{SaleCondition: Condition of sale}

No NAs. Values are categorical.

\begin{verbatim}
   Normal   Normal Sale
   Abnorml  Abnormal Sale -  trade, foreclosure, short sale
   AdjLand  Adjoining Land Purchase
   Alloca   Allocation - two linked properties with separate deeds, typically condo with a garage unit  
   Family   Sale between family members
   Partial  Home was not completed when last assessed (associated with New Homes)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{SaleCondition <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{SaleCondition)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{SaleCondition)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Abnorml AdjLand  Alloca  Family  Normal Partial 
##     190      12      24      46    2402     245
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{SaleCondition))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Please return to the 5.2 Tabs menu to select other (groups of)
variables}

\#\#Label encoding/factorizing the remaining character variables
\{.tabset\}

At this point, I have made sure that all variables with NAs are taken
care of. However, I still need to also take care of the remaining
character variables that without missing values. Similar to the previous
section, I have created Tabs for groups of variables.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Charcol <-}\StringTok{ }\KeywordTok{names}\NormalTok{(all[,}\KeywordTok{sapply}\NormalTok{(all, is.character)])}
\NormalTok{Charcol}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "Street"       "LandContour"  "LandSlope"    "Neighborhood"
##  [5] "Condition1"   "Condition2"   "BldgType"     "HouseStyle"  
##  [9] "RoofStyle"    "RoofMatl"     "Foundation"   "Heating"     
## [13] "HeatingQC"    "CentralAir"   "PavedDrive"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cat}\NormalTok{(}\StringTok{'There are'}\NormalTok{, }\KeywordTok{length}\NormalTok{(Charcol), }\StringTok{'remaining columns with character values'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## There are 15 remaining columns with character values
\end{verbatim}

\#\#\#Foundation

\textbf{Foundation: Type of foundation}

\begin{verbatim}
    BrkTil          Brick & Tile
    CBlock          Cinder Block
    PConc           Poured Contrete 
    Slab            Slab
    Stone           Stone
    Wood            Wood
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#No ordinality, so converting into factors}
\NormalTok{all}\OperatorTok{$}\NormalTok{Foundation <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{Foundation)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Foundation)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## BrkTil CBlock  PConc   Slab  Stone   Wood 
##    311   1235   1308     49     11      5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Foundation))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Please return to the 5.3 Tabs menu to select other (groups of)
variables}

\#\#\#Heating and airco

There are 2 heating variables, and one that indicates Airco Yes/No.

\textbf{Heating: Type of heating}

\begin{verbatim}
   Floor    Floor Furnace
   GasA Gas forced warm air furnace
   GasW Gas hot water or steam heat
   Grav Gravity furnace 
   OthW Hot water or steam heat other than gas
   Wall Wall furnace
   
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#No ordinality, so converting into factors}
\NormalTok{all}\OperatorTok{$}\NormalTok{Heating <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{Heating)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Heating)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Floor  GasA  GasW  Grav  OthW  Wall 
##     1  2874    27     9     2     6
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Heating))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{HeatingQC: Heating quality and condition}

\begin{verbatim}
   Ex   Excellent
   Gd   Good
   TA   Average/Typical
   Fa   Fair
   Po   Poor
   
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#making the variable ordinal using the Qualities vector}
\NormalTok{all}\OperatorTok{$}\NormalTok{HeatingQC<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{HeatingQC, Qualities))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## The following `from` values were not present in `x`: None
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{HeatingQC)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    1    2    3    4    5 
##    3   92  857  474 1493
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{HeatingQC))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{CentralAir: Central air conditioning}

\begin{verbatim}
   N    No
   Y    Yes
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{CentralAir<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{CentralAir, }\KeywordTok{c}\NormalTok{(}\StringTok{'N'}\NormalTok{=}\DecValTok{0}\NormalTok{, }\StringTok{'Y'}\NormalTok{=}\DecValTok{1}\NormalTok{)))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{CentralAir)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1 
##  196 2723
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{CentralAir))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Please return to the 5.3 Tabs menu to select other (groups of)
variables}

\#\#\#Roof

There are 2 variables that deal with the roof of houses.

\textbf{RoofStyle: Type of roof}

\begin{verbatim}
   Flat Flat
   Gable    Gable
   Gambrel  Gabrel (Barn)
   Hip  Hip
   Mansard  Mansard
   Shed Shed
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#No ordinality, so converting into factors}
\NormalTok{all}\OperatorTok{$}\NormalTok{RoofStyle <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{RoofStyle)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{RoofStyle)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    Flat   Gable Gambrel     Hip Mansard    Shed 
##      20    2310      22     551      11       5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{RoofStyle))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{RoofMatl: Roof material}

\begin{verbatim}
   ClyTile  Clay or Tile
   CompShg  Standard (Composite) Shingle
   Membran  Membrane
   Metal    Metal
   Roll Roll
   Tar&Grv  Gravel & Tar
   WdShake  Wood Shakes
   WdShngl  Wood Shingles
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#No ordinality, so converting into factors}
\NormalTok{all}\OperatorTok{$}\NormalTok{RoofMatl <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{RoofMatl)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{RoofMatl)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## ClyTile CompShg Membran   Metal    Roll Tar&Grv WdShake WdShngl 
##       1    2876       1       1       1      23       9       7
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{RoofMatl))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Please return to the 5.3 Tabs menu to select other (groups of)
variables}

\#\#\#Land

2 variables that specify the flatness and slope of the propoerty.

\textbf{LandContour: Flatness of the property}

\begin{verbatim}
   Lvl  Near Flat/Level 
   Bnk  Banked - Quick and significant rise from street grade to building
   HLS  Hillside - Significant slope from side to side
   Low  Depression
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#No ordinality, so converting into factors}
\NormalTok{all}\OperatorTok{$}\NormalTok{LandContour <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{LandContour)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{LandContour)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Bnk  HLS  Low  Lvl 
##  117  120   60 2622
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{LandContour))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{LandSlope: Slope of property}

\begin{verbatim}
   Gtl  Gentle slope
   Mod  Moderate Slope  
   Sev  Severe Slope
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Ordinal, so label encoding}
\NormalTok{all}\OperatorTok{$}\NormalTok{LandSlope<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{LandSlope, }\KeywordTok{c}\NormalTok{(}\StringTok{'Sev'}\NormalTok{=}\DecValTok{0}\NormalTok{, }\StringTok{'Mod'}\NormalTok{=}\DecValTok{1}\NormalTok{, }\StringTok{'Gtl'}\NormalTok{=}\DecValTok{2}\NormalTok{)))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{LandSlope)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2 
##   16  125 2778
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{LandSlope))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Please return to the 5.3 Tabs menu to select other (groups of)
variables}

\#\#\#Dwelling

2 variables that specify the type and style of dwelling.

\textbf{BldgType: Type of dwelling}

\begin{verbatim}
   1Fam Single-family Detached  
   2FmCon   Two-family Conversion; originally built as one-family dwelling
   Duplx    Duplex
   TwnhsE   Townhouse End Unit
   TwnhsI   Townhouse Inside Unit
\end{verbatim}

This seems ordinal to me (single family detached=best). Let's check it
with visualization.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(BldgType), }\DataTypeTok{y=}\NormalTok{SalePrice)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'summary'}\NormalTok{, }\DataTypeTok{fun.y =} \StringTok{"median"}\NormalTok{, }\DataTypeTok{fill=}\StringTok{'blue'}\NormalTok{)}\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{100000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_label}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ ..count.., }\DataTypeTok{y =}\NormalTok{ ..count..))}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-76-1.pdf}

However, the visualization does not show ordinality.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#No ordinality, so converting into factors}
\NormalTok{all}\OperatorTok{$}\NormalTok{BldgType <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{BldgType)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{BldgType)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   1Fam 2fmCon Duplex  Twnhs TwnhsE 
##   2425     62    109     96    227
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{BldgType))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{HouseStyle: Style of dwelling}

\begin{verbatim}
   1Story   One story
   1.5Fin   One and one-half story: 2nd level finished
   1.5Unf   One and one-half story: 2nd level unfinished
   2Story   Two story
   2.5Fin   Two and one-half story: 2nd level finished
   2.5Unf   Two and one-half story: 2nd level unfinished
   SFoyer   Split Foyer
   SLvl Split Level
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#No ordinality, so converting into factors}
\NormalTok{all}\OperatorTok{$}\NormalTok{HouseStyle <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{HouseStyle)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{HouseStyle)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## 1.5Fin 1.5Unf 1Story 2.5Fin 2.5Unf 2Story SFoyer   SLvl 
##    314     19   1471      8     24    872     83    128
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{HouseStyle))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Please return to the 5.3 Tabs menu to select other (groups of)
variables}

\#\#\#Neighborhood and Conditions

3 variables that specify the physical location, and the proximity of
`conditions'.

\textbf{Neighborhood: Physical locations within Ames city limits}

Note: as the number of levels is really high, I will look into binning
later on.

\begin{verbatim}
   Blmngtn  Bloomington Heights
   Blueste  Bluestem
   BrDale   Briardale
   BrkSide  Brookside
   ClearCr  Clear Creek
   CollgCr  College Creek
   Crawfor  Crawford
   Edwards  Edwards
   Gilbert  Gilbert
   IDOTRR   Iowa DOT and Rail Road
   MeadowV  Meadow Village
   Mitchel  Mitchell
   Names    North Ames
   NoRidge  Northridge
   NPkVill  Northpark Villa
   NridgHt  Northridge Heights
   NWAmes   Northwest Ames
   OldTown  Old Town
   SWISU    South & West of Iowa State University
   Sawyer   Sawyer
   SawyerW  Sawyer West
   Somerst  Somerset
   StoneBr  Stone Brook
   Timber   Timberland
   Veenker  Veenker
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#No ordinality, so converting into factors}
\NormalTok{all}\OperatorTok{$}\NormalTok{Neighborhood <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{Neighborhood)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Neighborhood)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Blmngtn Blueste  BrDale BrkSide ClearCr CollgCr Crawfor Edwards Gilbert 
##      28      10      30     108      44     267     103     194     165 
##  IDOTRR MeadowV Mitchel   NAmes NoRidge NPkVill NridgHt  NWAmes OldTown 
##      93      37     114     443      71      23     166     131     239 
##  Sawyer SawyerW Somerst StoneBr   SWISU  Timber Veenker 
##     151     125     182      51      48      72      24
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Neighborhood))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Condition1: Proximity to various conditions}

\begin{verbatim}
   Artery   Adjacent to arterial street
   Feedr    Adjacent to feeder street   
   Norm Normal  
   RRNn Within 200' of North-South Railroad
   RRAn Adjacent to North-South Railroad
   PosN Near positive off-site feature--park, greenbelt, etc.
   PosA Adjacent to postive off-site feature
   RRNe Within 200' of East-West Railroad
   RRAe Adjacent to East-West Railroad
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#No ordinality, so converting into factors}
\NormalTok{all}\OperatorTok{$}\NormalTok{Condition1 <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{Condition1)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Condition1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Artery  Feedr   Norm   PosA   PosN   RRAe   RRAn   RRNe   RRNn 
##     92    164   2511     20     39     28     50      6      9
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Condition1))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Condition2: Proximity to various conditions (if more than one is
present)}

\begin{verbatim}
   Artery   Adjacent to arterial street
   Feedr    Adjacent to feeder street   
   Norm Normal  
   RRNn Within 200' of North-South Railroad
   RRAn Adjacent to North-South Railroad
   PosN Near positive off-site feature--park, greenbelt, etc.
   PosA Adjacent to postive off-site feature
   RRNe Within 200' of East-West Railroad
   RRAe Adjacent to East-West Railroad
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#No ordinality, so converting into factors}
\NormalTok{all}\OperatorTok{$}\NormalTok{Condition2 <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{Condition2)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Condition2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Artery  Feedr   Norm   PosA   PosN   RRAe   RRAn   RRNn 
##      5     13   2889      4      4      1      1      2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Condition2))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Please return to the 5.3 Tabs menu to select other (groups of)
variables}

\#\#\#Pavement of Street \& Driveway

2 variables

\textbf{Street: Type of road access to property}

\begin{verbatim}
   Grvl Gravel  
   Pave Paved
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Ordinal, so label encoding}
\NormalTok{all}\OperatorTok{$}\NormalTok{Street<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{Street, }\KeywordTok{c}\NormalTok{(}\StringTok{'Grvl'}\NormalTok{=}\DecValTok{0}\NormalTok{, }\StringTok{'Pave'}\NormalTok{=}\DecValTok{1}\NormalTok{)))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Street)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1 
##   12 2907
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{Street))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{PavedDrive: Paved driveway}

\begin{verbatim}
   Y    Paved 
   P    Partial Pavement
   N    Dirt/Gravel
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#Ordinal, so label encoding}
\NormalTok{all}\OperatorTok{$}\NormalTok{PavedDrive<-}\KeywordTok{as.integer}\NormalTok{(}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{PavedDrive, }\KeywordTok{c}\NormalTok{(}\StringTok{'N'}\NormalTok{=}\DecValTok{0}\NormalTok{, }\StringTok{'P'}\NormalTok{=}\DecValTok{1}\NormalTok{, }\StringTok{'Y'}\NormalTok{=}\DecValTok{2}\NormalTok{)))}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{PavedDrive)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2 
##  216   62 2641
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{sum}\NormalTok{(}\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{PavedDrive))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2919
\end{verbatim}

\textbf{Please return to the 5.3 Tabs menu to select other (groups of)
variables}

\#\#Changing some numeric variables into factors

At this point, all variables are complete (No NAs), and all character
variables are converted into either numeric labels of into factors.
However, there are 3 variables that are recorded numeric but should
actually be categorical.

\#\#\#Year and Month Sold

While oridinality within YearBuilt (or remodeled) makes sense (old
houses are worth less), we are talking about only 5 years of sales.
These years also include an economic crisis. For instance: Sale Prices
in 2009 (after the collapse) are very likely to be much lower than in
2007. I wil convert YrSold into a factor before modeling, but as I need
the numeric version of YrSold to create an Age variable, I am not doing
that yet.

Month Sold is also an Integer variable. However, December is not
``better'' than January. Therefore, I will convert MoSold values back
into factors.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(all}\OperatorTok{$}\NormalTok{YrSold)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  int [1:2919] 2008 2007 2008 2006 2008 2009 2007 2009 2008 2008 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(all}\OperatorTok{$}\NormalTok{MoSold)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  int [1:2919] 2 5 9 2 12 10 8 11 4 1 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{MoSold <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{MoSold)}
\end{Highlighting}
\end{Shaded}

Although possible a bit less steep than expected, the effects of the
Banking crises that took place at the end of 2007 can be seen indeed.
After the highest median prices in 2007, the prices gradually decreased.
However, seasonality seems to play a bigger role, as you can see below.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ys <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(YrSold), }\DataTypeTok{y=}\NormalTok{SalePrice)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'summary'}\NormalTok{, }\DataTypeTok{fun.y =} \StringTok{"median"}\NormalTok{, }\DataTypeTok{fill=}\StringTok{'blue'}\NormalTok{)}\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{25000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_label}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ ..count.., }\DataTypeTok{y =}\NormalTok{ ..count..)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{coord_cartesian}\NormalTok{(}\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{200000}\NormalTok{)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept=}\DecValTok{163000}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{"dashed"}\NormalTok{, }\DataTypeTok{color =} \StringTok{"red"}\NormalTok{) }\CommentTok{#dashed line is median SalePrice}

\NormalTok{ms <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{MoSold, }\DataTypeTok{y=}\NormalTok{SalePrice)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'summary'}\NormalTok{, }\DataTypeTok{fun.y =} \StringTok{"median"}\NormalTok{, }\DataTypeTok{fill=}\StringTok{'blue'}\NormalTok{)}\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{25000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_label}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ ..count.., }\DataTypeTok{y =}\NormalTok{ ..count..)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{coord_cartesian}\NormalTok{(}\DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{200000}\NormalTok{)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept=}\DecValTok{163000}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{"dashed"}\NormalTok{, }\DataTypeTok{color =} \StringTok{"red"}\NormalTok{) }\CommentTok{#dashed line is median SalePrice}

\KeywordTok{grid.arrange}\NormalTok{(ys, ms, }\DataTypeTok{widths=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-85-1.pdf}

\#\#\#MSSubClass

MSSubClass: Identifies the type of dwelling involved in the sale.

\begin{verbatim}
    20  1-STORY 1946 & NEWER ALL STYLES
    30  1-STORY 1945 & OLDER
    40  1-STORY W/FINISHED ATTIC ALL AGES
    45  1-1/2 STORY - UNFINISHED ALL AGES
    50  1-1/2 STORY FINISHED ALL AGES
    60  2-STORY 1946 & NEWER
    70  2-STORY 1945 & OLDER
    75  2-1/2 STORY ALL AGES
    80  SPLIT OR MULTI-LEVEL
    85  SPLIT FOYER
    90  DUPLEX - ALL STYLES AND AGES
   120  1-STORY PUD (Planned Unit Development) - 1946 & NEWER
   150  1-1/2 STORY PUD - ALL AGES
   160  2-STORY PUD - 1946 & NEWER
   180  PUD - MULTILEVEL - INCL SPLIT LEV/FOYER
   190  2 FAMILY CONVERSION - ALL STYLES AND AGES
\end{verbatim}

These classes are coded as numbers, but really are categories.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(all}\OperatorTok{$}\NormalTok{MSSubClass)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  int [1:2919] 60 20 60 70 60 50 20 60 50 190 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{MSSubClass <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{MSSubClass)}

\CommentTok{#revalue for better readability}
\NormalTok{all}\OperatorTok{$}\NormalTok{MSSubClass<-}\KeywordTok{revalue}\NormalTok{(all}\OperatorTok{$}\NormalTok{MSSubClass, }\KeywordTok{c}\NormalTok{(}\StringTok{'20'}\NormalTok{=}\StringTok{'1 story 1946+'}\NormalTok{, }\StringTok{'30'}\NormalTok{=}\StringTok{'1 story 1945-'}\NormalTok{, }\StringTok{'40'}\NormalTok{=}\StringTok{'1 story unf attic'}\NormalTok{, }\StringTok{'45'}\NormalTok{=}\StringTok{'1,5 story unf'}\NormalTok{, }\StringTok{'50'}\NormalTok{=}\StringTok{'1,5 story fin'}\NormalTok{, }\StringTok{'60'}\NormalTok{=}\StringTok{'2 story 1946+'}\NormalTok{, }\StringTok{'70'}\NormalTok{=}\StringTok{'2 story 1945-'}\NormalTok{, }\StringTok{'75'}\NormalTok{=}\StringTok{'2,5 story all ages'}\NormalTok{, }\StringTok{'80'}\NormalTok{=}\StringTok{'split/multi level'}\NormalTok{, }\StringTok{'85'}\NormalTok{=}\StringTok{'split foyer'}\NormalTok{, }\StringTok{'90'}\NormalTok{=}\StringTok{'duplex all style/age'}\NormalTok{, }\StringTok{'120'}\NormalTok{=}\StringTok{'1 story PUD 1946+'}\NormalTok{, }\StringTok{'150'}\NormalTok{=}\StringTok{'1,5 story PUD all'}\NormalTok{, }\StringTok{'160'}\NormalTok{=}\StringTok{'2 story PUD 1946+'}\NormalTok{, }\StringTok{'180'}\NormalTok{=}\StringTok{'PUD multilevel'}\NormalTok{, }\StringTok{'190'}\NormalTok{=}\StringTok{'2 family conversion'}\NormalTok{))}

\KeywordTok{str}\NormalTok{(all}\OperatorTok{$}\NormalTok{MSSubClass)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  Factor w/ 16 levels "1 story 1946+",..: 6 1 6 7 6 5 1 6 5 16 ...
\end{verbatim}

\#Visualization of important variables

I have now finally reached the point where all character variables have
been converted into categorical factors or have been label encoded into
numbers. In addition, 3 numeric variables have been converted into
factors, and I deleted one variable (Utilities). As you can see below,
the number of numerical variables is now 56 (including the response
variable), and the remaining 23 variables are categorical.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{numericVars <-}\StringTok{ }\KeywordTok{which}\NormalTok{(}\KeywordTok{sapply}\NormalTok{(all, is.numeric)) }\CommentTok{#index vector numeric variables}
\NormalTok{factorVars <-}\StringTok{ }\KeywordTok{which}\NormalTok{(}\KeywordTok{sapply}\NormalTok{(all, is.factor)) }\CommentTok{#index vector factor variables}
\KeywordTok{cat}\NormalTok{(}\StringTok{'There are'}\NormalTok{, }\KeywordTok{length}\NormalTok{(numericVars), }\StringTok{'numeric variables, and'}\NormalTok{, }\KeywordTok{length}\NormalTok{(factorVars), }\StringTok{'categoric variables'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## There are 56 numeric variables, and 23 categoric variables
\end{verbatim}

\#\#Correlations again

Below I am checking the correlations again. As you can see, the number
of variables with a correlation of at least 0.5 with the SalePrice has
increased from 10 (see section 4.2.1) to 16.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all_numVar <-}\StringTok{ }\NormalTok{all[, numericVars]}
\NormalTok{cor_numVar <-}\StringTok{ }\KeywordTok{cor}\NormalTok{(all_numVar, }\DataTypeTok{use=}\StringTok{"pairwise.complete.obs"}\NormalTok{) }\CommentTok{#correlations of all numeric variables}

\CommentTok{#sort on decreasing correlations with SalePrice}
\NormalTok{cor_sorted <-}\StringTok{ }\KeywordTok{as.matrix}\NormalTok{(}\KeywordTok{sort}\NormalTok{(cor_numVar[,}\StringTok{'SalePrice'}\NormalTok{], }\DataTypeTok{decreasing =} \OtherTok{TRUE}\NormalTok{))}
 \CommentTok{#select only high corelations}
\NormalTok{CorHigh <-}\StringTok{ }\KeywordTok{names}\NormalTok{(}\KeywordTok{which}\NormalTok{(}\KeywordTok{apply}\NormalTok{(cor_sorted, }\DecValTok{1}\NormalTok{, }\ControlFlowTok{function}\NormalTok{(x) }\KeywordTok{abs}\NormalTok{(x)}\OperatorTok{>}\FloatTok{0.5}\NormalTok{)))}
\NormalTok{cor_numVar <-}\StringTok{ }\NormalTok{cor_numVar[CorHigh, CorHigh]}

\KeywordTok{corrplot.mixed}\NormalTok{(cor_numVar, }\DataTypeTok{tl.col=}\StringTok{"black"}\NormalTok{, }\DataTypeTok{tl.pos =} \StringTok{"lt"}\NormalTok{, }\DataTypeTok{tl.cex =} \FloatTok{0.7}\NormalTok{,}\DataTypeTok{cl.cex =} \FloatTok{.7}\NormalTok{, }\DataTypeTok{number.cex=}\NormalTok{.}\DecValTok{7}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-88-1}

\#\#Finding variable importance with a quick Random Forest

Although the correlations are giving a good overview of the most
important numeric variables and multicolinerity among those variables, I
wanted to get an overview of the most important variables including the
categorical variables before moving on to visualization.

I tried to get the relative importance of variables with a quick linear
regression model with the calc.relimp function of package , and also
tried the boruta function of package boruta which separates the
variables into groups that are important or not. However, these method
took a long time. As I only want to get an indication of the variable
importance, I eventually decided to keep it simple and just use a quick
and dirty Random Forest model with only 100 trees. This also does the
job for me, and does not take very long as I can specify a (relatively)
small number of trees.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{2018}\NormalTok{)}
\NormalTok{quick_RF <-}\StringTok{ }\KeywordTok{randomForest}\NormalTok{(}\DataTypeTok{x=}\NormalTok{all[}\DecValTok{1}\OperatorTok{:}\DecValTok{1460}\NormalTok{,}\OperatorTok{-}\DecValTok{79}\NormalTok{], }\DataTypeTok{y=}\NormalTok{all}\OperatorTok{$}\NormalTok{SalePrice[}\DecValTok{1}\OperatorTok{:}\DecValTok{1460}\NormalTok{], }\DataTypeTok{ntree=}\DecValTok{100}\NormalTok{,}\DataTypeTok{importance=}\OtherTok{TRUE}\NormalTok{)}
\NormalTok{imp_RF <-}\StringTok{ }\KeywordTok{importance}\NormalTok{(quick_RF)}
\NormalTok{imp_DF <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{Variables =} \KeywordTok{row.names}\NormalTok{(imp_RF), }\DataTypeTok{MSE =}\NormalTok{ imp_RF[,}\DecValTok{1}\NormalTok{])}
\NormalTok{imp_DF <-}\StringTok{ }\NormalTok{imp_DF[}\KeywordTok{order}\NormalTok{(imp_DF}\OperatorTok{$}\NormalTok{MSE, }\DataTypeTok{decreasing =} \OtherTok{TRUE}\NormalTok{),]}

\KeywordTok{ggplot}\NormalTok{(imp_DF[}\DecValTok{1}\OperatorTok{:}\DecValTok{20}\NormalTok{,], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{reorder}\NormalTok{(Variables, MSE), }\DataTypeTok{y=}\NormalTok{MSE, }\DataTypeTok{fill=}\NormalTok{MSE)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat =} \StringTok{'identity'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{'Variables'}\NormalTok{, }\DataTypeTok{y=} \StringTok{'% increase MSE if variable is randomly permuted'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{coord_flip}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{legend.position=}\StringTok{"none"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-89-1.pdf}

Only 3 of those most important variables are categorical according to
RF; Neighborhood, MSSubClass, and GarageType.

\hypertarget{above-ground-living-area-and-other-surface-related-variables-in-square-feet}{%
\subsubsection{Above Ground Living Area, and other surface related
variables (in square
feet)}\label{above-ground-living-area-and-other-surface-related-variables-in-square-feet}}

As I have already visualized the relation between the Above Ground
Living Area and SalePrice in my initial explorations, I will now just
display the distribution itself. As there are more `square feet' surface
measurements in the Top 20, I am taking the opportunity to bundle them
in this section. Note: GarageArea is taken care of in the Garage
variables section.

I am also adding `Total Rooms Above Ground' (TotRmsAbvGrd) as this
variable is highly correlated with the Above Ground Living Area(0.81).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s1 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{ all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{GrLivArea)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_density}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Square feet living area'}\NormalTok{)}
\NormalTok{s2 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(TotRmsAbvGrd))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Rooms above Ground'}\NormalTok{)}
\NormalTok{s3 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{ all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{X1stFlrSF)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_density}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Square feet first floor'}\NormalTok{)}
\NormalTok{s4 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{ all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{X2ndFlrSF)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_density}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Square feet second floor'}\NormalTok{)}
\NormalTok{s5 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{ all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{TotalBsmtSF)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_density}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Square feet basement'}\NormalTok{)}
\NormalTok{s6 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{ all[all}\OperatorTok{$}\NormalTok{LotArea}\OperatorTok{<}\DecValTok{100000}\NormalTok{,], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{LotArea)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_density}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Square feet lot'}\NormalTok{)}
\NormalTok{s7 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{ all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{LotFrontage)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_density}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Linear feet lot frontage'}\NormalTok{)}
\NormalTok{s8 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{ all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{LowQualFinSF)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Low quality square feet 1st & 2nd'}\NormalTok{)}

\NormalTok{layout <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{8}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{7}\NormalTok{),}\DecValTok{4}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DataTypeTok{byrow=}\OtherTok{TRUE}\NormalTok{)}
\KeywordTok{multiplot}\NormalTok{(s1, s2, s3, s4, s5, s6, s7, s8, }\DataTypeTok{layout=}\NormalTok{layout)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-90-1}

I will investigate several of these variables for outliers later on. For
the lot visualization, I have already taken out the lots above 100,000
square feet (4 houses).

GrLivArea seemed to be just the total of square feet 1st and 2nd floor.
However, in a later version, I discovered that there is also a variable
called: LowQualFinSF: Low quality finished square feet (all floors). As
you can see above (Low quality square feet 1st and 2nd) almost all
houses have none of this (only 40 houses do have some). It turns out
that these square feet are actually included in the GrLivArea. The
correlation between those 3 variables and GrLivArea is exactely 1.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor}\NormalTok{(all}\OperatorTok{$}\NormalTok{GrLivArea, (all}\OperatorTok{$}\NormalTok{X1stFlrSF }\OperatorTok{+}\StringTok{ }\NormalTok{all}\OperatorTok{$}\NormalTok{X2ndFlrSF }\OperatorTok{+}\StringTok{ }\NormalTok{all}\OperatorTok{$}\NormalTok{LowQualFinSF))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{head}\NormalTok{(all[all}\OperatorTok{$}\NormalTok{LowQualFinSF}\OperatorTok{>}\DecValTok{0}\NormalTok{, }\KeywordTok{c}\NormalTok{(}\StringTok{'GrLivArea'}\NormalTok{, }\StringTok{'X1stFlrSF'}\NormalTok{, }\StringTok{'X2ndFlrSF'}\NormalTok{, }\StringTok{'LowQualFinSF'}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     GrLivArea X1stFlrSF X2ndFlrSF LowQualFinSF
## 52       1176       816         0          360
## 89       1526      1013         0          513
## 126       754       520         0          234
## 171      1382       854         0          528
## 186      3608      1518      1518          572
## 188      1656       808       704          144
\end{verbatim}

\#\#\#The most important categorical variable; Neighborhood

Th first graph shows the median SalePrice by Neighorhood. The frequency
(number of houses) of each Neighborhood in the train set is shown in the
labels.

The second graph below shows the frequencies across all data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n1 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{Neighborhood, }\DataTypeTok{y=}\NormalTok{SalePrice)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'summary'}\NormalTok{, }\DataTypeTok{fun.y =} \StringTok{"median"}\NormalTok{, }\DataTypeTok{fill=}\StringTok{'blue'}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{45}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{50000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_label}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ ..count.., }\DataTypeTok{y =}\NormalTok{ ..count..), }\DataTypeTok{size=}\DecValTok{3}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept=}\DecValTok{163000}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{"dashed"}\NormalTok{, }\DataTypeTok{color =} \StringTok{"red"}\NormalTok{) }\CommentTok{#dashed line is median SalePrice}
\NormalTok{n2 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{Neighborhood)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_label}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ ..count.., }\DataTypeTok{y =}\NormalTok{ ..count..), }\DataTypeTok{size=}\DecValTok{3}\NormalTok{)}\OperatorTok{+}
\StringTok{        }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{45}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{))}
\KeywordTok{grid.arrange}\NormalTok{(n1, n2)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-92-1}

\#\#\#Overall Quality, and other Quality variables

I have already visualized the relation between Overall Quality and
SalePrice in my initial explorations, but I want to visualize the
frequency distribution as well. As there are more quality measurements,
I am taking the opportunity to bundle them in this section.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{q1 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(OverallQual))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}
\NormalTok{q2 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(ExterQual))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}
\NormalTok{q3 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(BsmtQual))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}
\NormalTok{q4 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(KitchenQual))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}
\NormalTok{q5 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(GarageQual))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}
\NormalTok{q6 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(FireplaceQu))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}
\NormalTok{q7 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(PoolQC))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}

\NormalTok{layout <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{8}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{8}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{7}\NormalTok{),}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DataTypeTok{byrow=}\OtherTok{TRUE}\NormalTok{)}
\KeywordTok{multiplot}\NormalTok{(q1, q2, q3, q4, q5, q6, q7, }\DataTypeTok{layout=}\NormalTok{layout)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-93-1}

Overall Quality is very important, and also more granular than the other
variables. External Quality is also improtant, but has a high
correlation with Overall Quality (0.73). Kitchen Quality also seems one
to keep, as all houses have a kitchen and there is a variance with some
substance. Garage Quality does not seem to distinguish much, as the
majority of garages have Q3. Fireplace Quality is in the list of high
correlations, and in the important variables list. The PoolQC is just
very sparse (the 13 pools cannot even be seen on this scale). I will
look at creating a `has pool' variable later on.

\#\#\#The second most important categorical variable; MSSubClass

The first visualization shows the median SalePrice by MSSubClass. The
frequency (number of houses) of each MSSubClass in the train set is
shown in the labels.

The histrogram shows the frequencies across all data. Most houses are
relatively new, and have one or two stories.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ms1 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{MSSubClass, }\DataTypeTok{y=}\NormalTok{SalePrice)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'summary'}\NormalTok{, }\DataTypeTok{fun.y =} \StringTok{"median"}\NormalTok{, }\DataTypeTok{fill=}\StringTok{'blue'}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{45}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{50000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_label}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ ..count.., }\DataTypeTok{y =}\NormalTok{ ..count..), }\DataTypeTok{size=}\DecValTok{3}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept=}\DecValTok{163000}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{"dashed"}\NormalTok{, }\DataTypeTok{color =} \StringTok{"red"}\NormalTok{) }\CommentTok{#dashed line is median SalePrice}
\NormalTok{ms2 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{MSSubClass)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_label}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ ..count.., }\DataTypeTok{y =}\NormalTok{ ..count..), }\DataTypeTok{size=}\DecValTok{3}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{45}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{))}
\KeywordTok{grid.arrange}\NormalTok{(ms1, ms2)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-94-1}

\#\#\#Garage variables

Several Garage variables have a high correlation with SalePrice, and are
also in the top-20 list of the quick random forest. However, there is
multicolinearity among them and I think that 7 garage variables is too
many anyway. I feel that something like 3 variables should be sufficient
(possibly GarageCars, GarageType, and a Quality measurement), but before
I do any selection I am visualizing all of them in this section.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#correct error}
\NormalTok{all}\OperatorTok{$}\NormalTok{GarageYrBlt[}\DecValTok{2593}\NormalTok{] <-}\StringTok{ }\DecValTok{2007} \CommentTok{#this must have been a typo. GarageYrBlt=2207, YearBuilt=2006, YearRemodAdd=2007.}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{g1 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all[all}\OperatorTok{$}\NormalTok{GarageCars }\OperatorTok{!=}\DecValTok{0}\NormalTok{,], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{GarageYrBlt)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{()}
\NormalTok{g2 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(GarageCars))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}
\NormalTok{g3 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{ all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{GarageArea)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_density}\NormalTok{()}
\NormalTok{g4 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(GarageCond))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}
\NormalTok{g5 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{GarageType)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}
\NormalTok{g6 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(GarageQual))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}
\NormalTok{g7 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(GarageFinish))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}

\NormalTok{layout <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{8}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{7}\NormalTok{),}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DataTypeTok{byrow=}\OtherTok{TRUE}\NormalTok{)}
\KeywordTok{multiplot}\NormalTok{(g1, g2, g3, g4, g5, g6, g7, }\DataTypeTok{layout=}\NormalTok{layout)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-96-1}

As already mentioned in section 4.2, GarageCars and GarageArea are
highly correlated. Here, GarageQual and GarageCond also seem highly
correlated, and both are dominated by level =3.

\#\#\#Basement variables

Similar the garage variables, multiple basement variables are important
in the correlations matrix and the Top 20 RF predictors list. However,
11 basement variables seems an overkill. Before I decide what I am going
to do with them, I am visualizing 8 of them below. The 2 ``Bathroom''
variables are dealt with in Feature Engineering (section 7.1), and the
``Basement square feet'' is already discussed in section 6.2.1.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{b1 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{BsmtFinSF1)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Type 1 finished square feet'}\NormalTok{)}
\NormalTok{b2 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{BsmtFinSF2)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{()}\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Type 2 finished square feet'}\NormalTok{)}
\NormalTok{b3 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{BsmtUnfSF)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{()}\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Unfinished square feet'}\NormalTok{)}
\NormalTok{b4 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(BsmtFinType1))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Rating of Type 1 finished area'}\NormalTok{)}
\NormalTok{b5 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(BsmtFinType2))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Rating of Type 2 finished area'}\NormalTok{)}
\NormalTok{b6 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(BsmtQual))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Height of the basement'}\NormalTok{)}
\NormalTok{b7 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(BsmtCond))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Rating of general condition'}\NormalTok{)}
\NormalTok{b8 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(BsmtExposure))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Walkout or garden level walls'}\NormalTok{)}

\NormalTok{layout <-}\StringTok{ }\KeywordTok{matrix}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{,}\DecValTok{9}\NormalTok{,}\DecValTok{6}\NormalTok{,}\DecValTok{7}\NormalTok{,}\DecValTok{8}\NormalTok{),}\DecValTok{3}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DataTypeTok{byrow=}\OtherTok{TRUE}\NormalTok{)}
\KeywordTok{multiplot}\NormalTok{(b1, b2, b3, b4, b5, b6, b7, b8, }\DataTypeTok{layout=}\NormalTok{layout)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-97-1}

So it seemed as if the Total Basement Surface in square feet
(TotalBsmtSF) is further broken down into finished areas (2 if more than
one type of finish), and unfinished area. I did a check between the
correlation of total of those 3 variables, and TotalBsmtSF. The
correlation is exactely 1, so that's a good thing (no errors or small
discrepancies)!

Basement Quality is a confusing variable name, as it turns out that it
specifically rates the Height of the basement.

\#Feature engineering

\#\#Total number of Bathrooms

There are 4 bathroom variables. Individually, these variables are not
very important. However, I assume that I if I add them up into one
predictor, this predictor is likely to become a strong one.

``A half-bath, also known as a powder room or guest bath, has only two
of the four main bathroom components-typically a toilet and sink.''
Consequently, I will also count the half bathrooms as half.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{TotBathrooms <-}\StringTok{ }\NormalTok{all}\OperatorTok{$}\NormalTok{FullBath }\OperatorTok{+}\StringTok{ }\NormalTok{(all}\OperatorTok{$}\NormalTok{HalfBath}\OperatorTok{*}\FloatTok{0.5}\NormalTok{) }\OperatorTok{+}\StringTok{ }\NormalTok{all}\OperatorTok{$}\NormalTok{BsmtFullBath }\OperatorTok{+}\StringTok{ }\NormalTok{(all}\OperatorTok{$}\NormalTok{BsmtHalfBath}\OperatorTok{*}\FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

As you can see in the first graph, there now seems to be a clear
correlation (it's 0.63). The frequency distribution of Bathrooms in all
data is shown in the second graph.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tb1 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(TotBathrooms), }\DataTypeTok{y=}\NormalTok{SalePrice))}\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{col=}\StringTok{'blue'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{se=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{color=}\StringTok{"black"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{group=}\DecValTok{1}\NormalTok{)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{100000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma)}
\NormalTok{tb2 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(TotBathrooms))) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'count'}\NormalTok{)}
\KeywordTok{grid.arrange}\NormalTok{(tb1, tb2)}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-99-1.pdf}

\#\#Adding `House Age', `Remodeled (Yes/No)', and IsNew variables

Altogether, there are 3 variables that are relevant with regards to the
Age of a house; YearBlt, YearRemodAdd, and YearSold. YearRemodAdd
defaults to YearBuilt if there has been no Remodeling/Addition. I will
use YearRemodeled and YearSold to determine the Age. However, as parts
of old constructions will always remain and only parts of the house
might have been renovated, I will also introduce a Remodeled Yes/No
variable. This should be seen as some sort of penalty parameter that
indicates that if the Age is based on a remodeling date, it is probably
worth less than houses that were built from scratch in that same year.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{Remod <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(all}\OperatorTok{$}\NormalTok{YearBuilt}\OperatorTok{==}\NormalTok{all}\OperatorTok{$}\NormalTok{YearRemodAdd, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{) }\CommentTok{#0=No Remodeling, 1=Remodeling}
\NormalTok{all}\OperatorTok{$}\NormalTok{Age <-}\StringTok{ }\KeywordTok{as.numeric}\NormalTok{(all}\OperatorTok{$}\NormalTok{YrSold)}\OperatorTok{-}\NormalTok{all}\OperatorTok{$}\NormalTok{YearRemodAdd}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{Age, }\DataTypeTok{y=}\NormalTok{SalePrice))}\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{col=}\StringTok{'blue'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{se=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{color=}\StringTok{"black"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{group=}\DecValTok{1}\NormalTok{)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{100000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma)}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-101-1.pdf}

As expected, the graph shows a negative correlation with Age (old house
are worth less).

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice)], all}\OperatorTok{$}\NormalTok{Age[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.5090787
\end{verbatim}

As you can see below, houses that are remodeled are worth less indeed,
as expected.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(Remod), }\DataTypeTok{y=}\NormalTok{SalePrice)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'summary'}\NormalTok{, }\DataTypeTok{fun.y =} \StringTok{"median"}\NormalTok{, }\DataTypeTok{fill=}\StringTok{'blue'}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_label}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ ..count.., }\DataTypeTok{y =}\NormalTok{ ..count..), }\DataTypeTok{size=}\DecValTok{6}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{50000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma) }\OperatorTok{+}
\StringTok{        }\KeywordTok{theme_grey}\NormalTok{(}\DataTypeTok{base_size =} \DecValTok{18}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept=}\DecValTok{163000}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{"dashed"}\NormalTok{) }\CommentTok{#dashed line is median SalePrice}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=0.5\linewidth]{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-103-1}

Finally, I am creating the IsNew variable below. Altogether, there are
116 new houses in the dataset.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{IsNew <-}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(all}\OperatorTok{$}\NormalTok{YrSold}\OperatorTok{==}\NormalTok{all}\OperatorTok{$}\NormalTok{YearBuilt, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{IsNew)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1 
## 2803  116
\end{verbatim}

These 116 new houses are fairly evenly distributed among train and test
set, and as you can see new houses are worth considerably more on
average.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{as.factor}\NormalTok{(IsNew), }\DataTypeTok{y=}\NormalTok{SalePrice)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'summary'}\NormalTok{, }\DataTypeTok{fun.y =} \StringTok{"median"}\NormalTok{, }\DataTypeTok{fill=}\StringTok{'blue'}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_label}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ ..count.., }\DataTypeTok{y =}\NormalTok{ ..count..), }\DataTypeTok{size=}\DecValTok{6}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{50000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma) }\OperatorTok{+}
\StringTok{        }\KeywordTok{theme_grey}\NormalTok{(}\DataTypeTok{base_size =} \DecValTok{18}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept=}\DecValTok{163000}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{"dashed"}\NormalTok{) }\CommentTok{#dashed line is median SalePrice}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=0.5\linewidth]{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-105-1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{YrSold <-}\StringTok{ }\KeywordTok{as.factor}\NormalTok{(all}\OperatorTok{$}\NormalTok{YrSold) }\CommentTok{#the numeric version is now not needed anymore}
\end{Highlighting}
\end{Shaded}

\#\#Binning Neighborhood

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nb1 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{reorder}\NormalTok{(Neighborhood, SalePrice, }\DataTypeTok{FUN=}\NormalTok{median), }\DataTypeTok{y=}\NormalTok{SalePrice)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'summary'}\NormalTok{, }\DataTypeTok{fun.y =} \StringTok{"median"}\NormalTok{, }\DataTypeTok{fill=}\StringTok{'blue'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Neighborhood'}\NormalTok{, }\DataTypeTok{y=}\StringTok{'Median SalePrice'}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{45}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{50000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_label}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ ..count.., }\DataTypeTok{y =}\NormalTok{ ..count..), }\DataTypeTok{size=}\DecValTok{3}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept=}\DecValTok{163000}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{"dashed"}\NormalTok{, }\DataTypeTok{color =} \StringTok{"red"}\NormalTok{) }\CommentTok{#dashed line is median SalePrice}
\NormalTok{nb2 <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{reorder}\NormalTok{(Neighborhood, SalePrice, }\DataTypeTok{FUN=}\NormalTok{mean), }\DataTypeTok{y=}\NormalTok{SalePrice)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{'summary'}\NormalTok{, }\DataTypeTok{fun.y =} \StringTok{"mean"}\NormalTok{, }\DataTypeTok{fill=}\StringTok{'blue'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x=}\StringTok{'Neighborhood'}\NormalTok{, }\DataTypeTok{y=}\StringTok{"Mean SalePrice"}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{theme}\NormalTok{(}\DataTypeTok{axis.text.x =} \KeywordTok{element_text}\NormalTok{(}\DataTypeTok{angle =} \DecValTok{45}\NormalTok{, }\DataTypeTok{hjust =} \DecValTok{1}\NormalTok{)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{50000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_label}\NormalTok{(}\DataTypeTok{stat =} \StringTok{"count"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =}\NormalTok{ ..count.., }\DataTypeTok{y =}\NormalTok{ ..count..), }\DataTypeTok{size=}\DecValTok{3}\NormalTok{) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept=}\DecValTok{163000}\NormalTok{, }\DataTypeTok{linetype=}\StringTok{"dashed"}\NormalTok{, }\DataTypeTok{color =} \StringTok{"red"}\NormalTok{) }\CommentTok{#dashed line is median SalePrice}
\KeywordTok{grid.arrange}\NormalTok{(nb1, nb2)}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-107-1.pdf}

Both the median and mean Saleprices agree on 3 neighborhoods with
substantially higher saleprices. The separation of the 3 relatively poor
neighborhoods is less clear, but at least both graphs agree on the same
3 poor neighborhoods. Since I do not want to `overbin', I am only
creating categories for those `extremes'.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{NeighRich[all}\OperatorTok{$}\NormalTok{Neighborhood }\OperatorTok{%in%}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'StoneBr'}\NormalTok{, }\StringTok{'NridgHt'}\NormalTok{, }\StringTok{'NoRidge'}\NormalTok{)] <-}\StringTok{ }\DecValTok{2}
\NormalTok{all}\OperatorTok{$}\NormalTok{NeighRich[}\OperatorTok{!}\NormalTok{all}\OperatorTok{$}\NormalTok{Neighborhood }\OperatorTok{%in%}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'MeadowV'}\NormalTok{, }\StringTok{'IDOTRR'}\NormalTok{, }\StringTok{'BrDale'}\NormalTok{, }\StringTok{'StoneBr'}\NormalTok{, }\StringTok{'NridgHt'}\NormalTok{, }\StringTok{'NoRidge'}\NormalTok{)] <-}\StringTok{ }\DecValTok{1}
\NormalTok{all}\OperatorTok{$}\NormalTok{NeighRich[all}\OperatorTok{$}\NormalTok{Neighborhood }\OperatorTok{%in%}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'MeadowV'}\NormalTok{, }\StringTok{'IDOTRR'}\NormalTok{, }\StringTok{'BrDale'}\NormalTok{)] <-}\StringTok{ }\DecValTok{0}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{table}\NormalTok{(all}\OperatorTok{$}\NormalTok{NeighRich)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##    0    1    2 
##  160 2471  288
\end{verbatim}

\#\#Total Square Feet

As the total living space generally is very important when people buy
houses, I am adding a predictors that adds up the living space above and
below ground.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{TotalSqFeet <-}\StringTok{ }\NormalTok{all}\OperatorTok{$}\NormalTok{GrLivArea }\OperatorTok{+}\StringTok{ }\NormalTok{all}\OperatorTok{$}\NormalTok{TotalBsmtSF}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{TotalSqFeet, }\DataTypeTok{y=}\NormalTok{SalePrice))}\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{col=}\StringTok{'blue'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{se=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{color=}\StringTok{"black"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{group=}\DecValTok{1}\NormalTok{)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{100000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma) }\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_text_repel}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label =} \KeywordTok{ifelse}\NormalTok{(all}\OperatorTok{$}\NormalTok{GrLivArea[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice)]}\OperatorTok{>}\DecValTok{4500}\NormalTok{, }\KeywordTok{rownames}\NormalTok{(all), }\StringTok{''}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-111-1.pdf}

As expected, the correlation with SalePrice is very strong indeed
(0.78).

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice, all}\OperatorTok{$}\NormalTok{TotalSqFeet, }\DataTypeTok{use=} \StringTok{"pairwise.complete.obs"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.7789588
\end{verbatim}

The two potential outliers seem to `outlie' even more than before. By
taking out these two outliers, the correlation increases by 5\%.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice[}\OperatorTok{-}\KeywordTok{c}\NormalTok{(}\DecValTok{524}\NormalTok{, }\DecValTok{1299}\NormalTok{)], all}\OperatorTok{$}\NormalTok{TotalSqFeet[}\OperatorTok{-}\KeywordTok{c}\NormalTok{(}\DecValTok{524}\NormalTok{, }\DecValTok{1299}\NormalTok{)], }\DataTypeTok{use=} \StringTok{"pairwise.complete.obs"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.829042
\end{verbatim}

\#\#Consolidating Porch variables

Below, I listed the variables that seem related regarding porches.

\begin{itemize}
\item
  WoodDeckSF: Wood deck area in square feet
\item
  OpenPorchSF: Open porch area in square feet
\item
  EnclosedPorch: Enclosed porch area in square feet
\item
  3SsnPorch: Three season porch area in square feet
\item
  ScreenPorch: Screen porch area in square feet
\end{itemize}

As far as I know, porches are sheltered areas outside of the house, and
a wooden deck is unsheltered. Therefore, I am leaving WoodDeckSF alone,
and are only consolidating the 4 porch variables.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{TotalPorchSF <-}\StringTok{ }\NormalTok{all}\OperatorTok{$}\NormalTok{OpenPorchSF }\OperatorTok{+}\StringTok{ }\NormalTok{all}\OperatorTok{$}\NormalTok{EnclosedPorch }\OperatorTok{+}\StringTok{ }\NormalTok{all}\OperatorTok{$}\NormalTok{X3SsnPorch }\OperatorTok{+}\StringTok{ }\NormalTok{all}\OperatorTok{$}\NormalTok{ScreenPorch}
\end{Highlighting}
\end{Shaded}

Although adding up these Porch areas makes sense (there should not be
any overlap between areas), the correlation with SalePrice is not very
strong.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{cor}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice, all}\OperatorTok{$}\NormalTok{TotalPorchSF, }\DataTypeTok{use=} \StringTok{"pairwise.complete.obs"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1957389
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(}\DataTypeTok{data=}\NormalTok{all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),], }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{TotalPorchSF, }\DataTypeTok{y=}\NormalTok{SalePrice))}\OperatorTok{+}
\StringTok{        }\KeywordTok{geom_point}\NormalTok{(}\DataTypeTok{col=}\StringTok{'blue'}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{se=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{color=}\StringTok{"black"}\NormalTok{, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{group=}\DecValTok{1}\NormalTok{)) }\OperatorTok{+}
\StringTok{        }\KeywordTok{scale_y_continuous}\NormalTok{(}\DataTypeTok{breaks=} \KeywordTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{800000}\NormalTok{, }\DataTypeTok{by=}\DecValTok{100000}\NormalTok{), }\DataTypeTok{labels =}\NormalTok{ comma)}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-116-1.pdf}

\#Preparing data for modeling

\#\#Dropping highly correlated variables

First of all, I am dropping a variable if two variables are highly
correlated. To find these correlated pairs, I have used the correlations
matrix again (see section 6.1). For instance: GarageCars and GarageArea
have a correlation of 0.89. Of those two, I am dropping the variable
with the lowest correlation with SalePrice (which is GarageArea with a
SalePrice correlation of 0.62. GarageCars has a SalePrice correlation of
0.64).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dropVars <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'YearRemodAdd'}\NormalTok{, }\StringTok{'GarageYrBlt'}\NormalTok{, }\StringTok{'GarageArea'}\NormalTok{, }\StringTok{'GarageCond'}\NormalTok{, }\StringTok{'TotalBsmtSF'}\NormalTok{, }\StringTok{'TotalRmsAbvGrd'}\NormalTok{, }\StringTok{'BsmtFinSF1'}\NormalTok{)}

\NormalTok{all <-}\StringTok{ }\NormalTok{all[,}\OperatorTok{!}\NormalTok{(}\KeywordTok{names}\NormalTok{(all) }\OperatorTok{%in%}\StringTok{ }\NormalTok{dropVars)]}
\end{Highlighting}
\end{Shaded}

\#\#Removing outliers

For the time being, I am keeping it simple and just remove the two
really big houses with low SalePrice manually. However, I intend to
investigate this more thorough in a later stage (possibly using the
`outliers' package).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all <-}\StringTok{ }\NormalTok{all[}\OperatorTok{-}\KeywordTok{c}\NormalTok{(}\DecValTok{524}\NormalTok{, }\DecValTok{1299}\NormalTok{),]}
\end{Highlighting}
\end{Shaded}

\#\#PreProcessing predictor variables

Before modeling I need to center and scale the `true numeric' predictors
(so not variables that have been label encoded), and create dummy
variables for the categorical predictors. Below, I am splitting the
dataframe into one with all (true) numeric variables, and another
dataframe holding the (ordinal) factors.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{numericVarNames <-}\StringTok{ }\NormalTok{numericVarNames[}\OperatorTok{!}\NormalTok{(numericVarNames }\OperatorTok{%in%}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'MSSubClass'}\NormalTok{, }\StringTok{'MoSold'}\NormalTok{, }\StringTok{'YrSold'}\NormalTok{, }\StringTok{'SalePrice'}\NormalTok{, }\StringTok{'OverallQual'}\NormalTok{, }\StringTok{'OverallCond'}\NormalTok{))] }\CommentTok{#numericVarNames was created before having done anything}
\NormalTok{numericVarNames <-}\StringTok{ }\KeywordTok{append}\NormalTok{(numericVarNames, }\KeywordTok{c}\NormalTok{(}\StringTok{'Age'}\NormalTok{, }\StringTok{'TotalPorchSF'}\NormalTok{, }\StringTok{'TotBathrooms'}\NormalTok{, }\StringTok{'TotalSqFeet'}\NormalTok{))}

\NormalTok{DFnumeric <-}\StringTok{ }\NormalTok{all[, }\KeywordTok{names}\NormalTok{(all) }\OperatorTok{%in%}\StringTok{ }\NormalTok{numericVarNames]}

\NormalTok{DFfactors <-}\StringTok{ }\NormalTok{all[, }\OperatorTok{!}\NormalTok{(}\KeywordTok{names}\NormalTok{(all) }\OperatorTok{%in%}\StringTok{ }\NormalTok{numericVarNames)]}
\NormalTok{DFfactors <-}\StringTok{ }\NormalTok{DFfactors[, }\KeywordTok{names}\NormalTok{(DFfactors) }\OperatorTok{!=}\StringTok{ 'SalePrice'}\NormalTok{]}

\KeywordTok{cat}\NormalTok{(}\StringTok{'There are'}\NormalTok{, }\KeywordTok{length}\NormalTok{(DFnumeric), }\StringTok{'numeric variables, and'}\NormalTok{, }\KeywordTok{length}\NormalTok{(DFfactors), }\StringTok{'factor variables'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## There are 30 numeric variables, and 49 factor variables
\end{verbatim}

\#\#\#Skewness and normalizing of the numeric predictors

\textbf{Skewness} Skewness is a measure of the symmetry in a
distribution. A symmetrical dataset will have a skewness equal to 0. So,
a normal distribution will have a skewness of 0. Skewness essentially
measures the relative size of the two tails. As a rule of thumb,
skewness should be between -1 and 1. In this range, data are considered
fairly symmetrical. In order to fix the skewness, I am taking the log
for all numeric predictors with an absolute skew greater than 0.8
(actually: log+1, to avoid division by zero issues).

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\OperatorTok{:}\KeywordTok{ncol}\NormalTok{(DFnumeric))\{}
        \ControlFlowTok{if}\NormalTok{ (}\KeywordTok{abs}\NormalTok{(}\KeywordTok{skew}\NormalTok{(DFnumeric[,i]))}\OperatorTok{>}\FloatTok{0.8}\NormalTok{)\{}
\NormalTok{                DFnumeric[,i] <-}\StringTok{ }\KeywordTok{log}\NormalTok{(DFnumeric[,i] }\OperatorTok{+}\DecValTok{1}\NormalTok{)}
\NormalTok{        \}}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\textbf{Normalizing the data}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{PreNum <-}\StringTok{ }\KeywordTok{preProcess}\NormalTok{(DFnumeric, }\DataTypeTok{method=}\KeywordTok{c}\NormalTok{(}\StringTok{"center"}\NormalTok{, }\StringTok{"scale"}\NormalTok{))}
\KeywordTok{print}\NormalTok{(PreNum)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Created from 2917 samples and 30 variables
## 
## Pre-processing:
##   - centered (30)
##   - ignored (0)
##   - scaled (30)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DFnorm <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(PreNum, DFnumeric)}
\KeywordTok{dim}\NormalTok{(DFnorm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2917   30
\end{verbatim}

\#\#\#One hot encoding the categorical variables

The last step needed to ensure that all predictors are converted into
numeric columns (which is required by most Machine Learning algorithms)
is to `one-hot encode' the categorical variables. This basically means
that all (not ordinal) factor values are getting a seperate colums with
1s and 0s (1 basically means Yes/Present). To do this one-hot encoding,
I am using the \texttt{model.matrix()} function.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DFdummies <-}\StringTok{ }\KeywordTok{as.data.frame}\NormalTok{(}\KeywordTok{model.matrix}\NormalTok{(}\OperatorTok{~}\NormalTok{.}\OperatorTok{-}\DecValTok{1}\NormalTok{, DFfactors))}
\KeywordTok{dim}\NormalTok{(DFdummies)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2917  201
\end{verbatim}

\#\#\#Removing levels with few or no observations in train or test

In previous versions, I worked with Caret's
\texttt{Near\ Zero\ Variance} function. Although this works, it also is
a quick fix and too much information got lost. For instance, by using
the defaults, all Neighborhoods with less than 146 houses are omitted as
(one-hot encoded) variables (frequency ratio higher than 95/5).
Therefore, I have taken amore carefull manual approach in this version.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#check if some values are absent in the test set}
\NormalTok{ZerocolTest <-}\StringTok{ }\KeywordTok{which}\NormalTok{(}\KeywordTok{colSums}\NormalTok{(DFdummies[(}\KeywordTok{nrow}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),])}\OperatorTok{+}\DecValTok{1}\NormalTok{)}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(all),])}\OperatorTok{==}\DecValTok{0}\NormalTok{)}
\KeywordTok{colnames}\NormalTok{(DFdummies[ZerocolTest])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "Condition2RRAe"     "Condition2RRAn"     "Condition2RRNn"    
##  [4] "HouseStyle2.5Fin"   "RoofMatlMembran"    "RoofMatlMetal"     
##  [7] "RoofMatlRoll"       "Exterior1stImStucc" "Exterior1stStone"  
## [10] "Exterior2ndOther"   "HeatingOthW"        "ElectricalMix"     
## [13] "MiscFeatureTenC"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DFdummies <-}\StringTok{ }\NormalTok{DFdummies[,}\OperatorTok{-}\NormalTok{ZerocolTest] }\CommentTok{#removing predictors}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#check if some values are absent in the train set}
\NormalTok{ZerocolTrain <-}\StringTok{ }\KeywordTok{which}\NormalTok{(}\KeywordTok{colSums}\NormalTok{(DFdummies[}\DecValTok{1}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),]),])}\OperatorTok{==}\DecValTok{0}\NormalTok{)}
\KeywordTok{colnames}\NormalTok{(DFdummies[ZerocolTrain])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "MSSubClass1,5 story PUD all"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DFdummies <-}\StringTok{ }\NormalTok{DFdummies[,}\OperatorTok{-}\NormalTok{ZerocolTrain] }\CommentTok{#removing predictor}
\end{Highlighting}
\end{Shaded}

Also taking out variables with less than 10 `ones' in the train set.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fewOnes <-}\StringTok{ }\KeywordTok{which}\NormalTok{(}\KeywordTok{colSums}\NormalTok{(DFdummies[}\DecValTok{1}\OperatorTok{:}\KeywordTok{nrow}\NormalTok{(all[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),]),])}\OperatorTok{<}\DecValTok{10}\NormalTok{)}
\KeywordTok{colnames}\NormalTok{(DFdummies[fewOnes])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "MSSubClass1 story unf attic" "LotConfigFR3"               
##  [3] "NeighborhoodBlueste"         "NeighborhoodNPkVill"        
##  [5] "Condition1PosA"              "Condition1RRNe"             
##  [7] "Condition1RRNn"              "Condition2Feedr"            
##  [9] "Condition2PosA"              "Condition2PosN"             
## [11] "RoofStyleMansard"            "RoofStyleShed"              
## [13] "RoofMatlWdShake"             "RoofMatlWdShngl"            
## [15] "Exterior1stAsphShn"          "Exterior1stBrkComm"         
## [17] "Exterior1stCBlock"           "Exterior2ndAsphShn"         
## [19] "Exterior2ndBrk Cmn"          "Exterior2ndCBlock"          
## [21] "Exterior2ndStone"            "FoundationStone"            
## [23] "FoundationWood"              "HeatingGrav"                
## [25] "HeatingWall"                 "ElectricalFuseP"            
## [27] "GarageTypeCarPort"           "MiscFeatureOthr"            
## [29] "SaleTypeCon"                 "SaleTypeConLD"              
## [31] "SaleTypeConLI"               "SaleTypeConLw"              
## [33] "SaleTypeCWD"                 "SaleTypeOth"                
## [35] "SaleConditionAdjLand"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DFdummies <-}\StringTok{ }\NormalTok{DFdummies[,}\OperatorTok{-}\NormalTok{fewOnes] }\CommentTok{#removing predictors}
\KeywordTok{dim}\NormalTok{(DFdummies)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2917  152
\end{verbatim}

Altogether, I have removed 49 one-hot encoded predictors with little or
no variance. Altough this may seem a significant number, it is actually
much less than the number of predictors that were taken out by using
caret's\texttt{near\ zero\ variance} function (using its default
thresholds).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{combined <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(DFnorm, DFdummies) }\CommentTok{#combining all (now numeric) predictors into one dataframe }
\end{Highlighting}
\end{Shaded}

\#\#Dealing with skewness of response variable

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{skew}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.877427
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qqnorm}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice)}
\KeywordTok{qqline}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice)}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-129-1.pdf}

The skew of 1.87 indicates a right skew that is too high, and the Q-Q
plot shows that sale prices are also not normally distributed. To fix
this I am taking the log of SalePrice.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{all}\OperatorTok{$}\NormalTok{SalePrice <-}\StringTok{ }\KeywordTok{log}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice) }\CommentTok{#default is the natural logarithm, "+1" is not necessary as there are no 0's}
\KeywordTok{skew}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1213182
\end{verbatim}

As you can see,the skew is now quite low and the Q-Q plot is also
looking much better.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qqnorm}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice)}
\KeywordTok{qqline}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice)}
\end{Highlighting}
\end{Shaded}

\includegraphics{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-131-1.pdf}

\#\#Composing train and test sets

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{train1 <-}\StringTok{ }\NormalTok{combined[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),]}
\NormalTok{test1 <-}\StringTok{ }\NormalTok{combined[}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice),]}
\end{Highlighting}
\end{Shaded}

\#Modeling

\#\#Lasso regression model

I have also tried Ridge and Elastic Net models, but since lasso gives
the best results of those 3 models I am only keeping the lasso model in
the document.

The elastic-net penalty is controlled by alpha, and bridges the gap
between lasso (alpha=1) and ridge (alpha=0). The tuning parameter lambda
controls the overall strength of the penalty. It is known that the ridge
penalty shrinks the coefficients of correlated predictors towards each
other while the lasso tends to pick one of them and discard the others.

Below, I am using caret cross validation to find the best value for
lambda, which is the only hyperparameter that needs to be tuned for the
lasso model.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{set.seed}\NormalTok{(}\DecValTok{27042018}\NormalTok{)}
\NormalTok{my_control <-}\KeywordTok{trainControl}\NormalTok{(}\DataTypeTok{method=}\StringTok{"cv"}\NormalTok{, }\DataTypeTok{number=}\DecValTok{5}\NormalTok{)}
\NormalTok{lassoGrid <-}\StringTok{ }\KeywordTok{expand.grid}\NormalTok{(}\DataTypeTok{alpha =} \DecValTok{1}\NormalTok{, }\DataTypeTok{lambda =} \KeywordTok{seq}\NormalTok{(}\FloatTok{0.001}\NormalTok{,}\FloatTok{0.1}\NormalTok{,}\DataTypeTok{by =} \FloatTok{0.0005}\NormalTok{))}

\NormalTok{lasso_mod <-}\StringTok{ }\KeywordTok{train}\NormalTok{(}\DataTypeTok{x=}\NormalTok{train1, }\DataTypeTok{y=}\NormalTok{all}\OperatorTok{$}\NormalTok{SalePrice[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice)], }\DataTypeTok{method=}\StringTok{'glmnet'}\NormalTok{, }\DataTypeTok{trControl=}\NormalTok{ my_control, }\DataTypeTok{tuneGrid=}\NormalTok{lassoGrid) }
\NormalTok{lasso_mod}\OperatorTok{$}\NormalTok{bestTune}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   alpha lambda
## 4     1 0.0025
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{min}\NormalTok{(lasso_mod}\OperatorTok{$}\NormalTok{results}\OperatorTok{$}\NormalTok{RMSE)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1121579
\end{verbatim}

The documentation of the caret `varImp' function says: for glmboost and
glmnet the absolute value of the coefficients corresponding to the tuned
model are used.

Although this means that a real ranking of the most important variables
is not stored, it gives me the opportunity to find out how many of the
variables are not used in the model (and hence have coefficient 0).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lassoVarImp <-}\StringTok{ }\KeywordTok{varImp}\NormalTok{(lasso_mod,}\DataTypeTok{scale=}\NormalTok{F)}
\NormalTok{lassoImportance <-}\StringTok{ }\NormalTok{lassoVarImp}\OperatorTok{$}\NormalTok{importance}

\NormalTok{varsSelected <-}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{which}\NormalTok{(lassoImportance}\OperatorTok{$}\NormalTok{Overall}\OperatorTok{!=}\DecValTok{0}\NormalTok{))}
\NormalTok{varsNotSelected <-}\StringTok{ }\KeywordTok{length}\NormalTok{(}\KeywordTok{which}\NormalTok{(lassoImportance}\OperatorTok{$}\NormalTok{Overall}\OperatorTok{==}\DecValTok{0}\NormalTok{))}

\KeywordTok{cat}\NormalTok{(}\StringTok{'Lasso uses'}\NormalTok{, varsSelected, }\StringTok{'variables in its model, and did not select'}\NormalTok{, varsNotSelected, }\StringTok{'variables.'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Lasso uses 100 variables in its model, and did not select 82 variables.
\end{verbatim}

So lasso did what it is supposed to do: it seems to have dealt with
multicolinearity well by not using about 45\% of the available variables
in the model.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LassoPred <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(lasso_mod, test1)}
\NormalTok{predictions_lasso <-}\StringTok{ }\KeywordTok{exp}\NormalTok{(LassoPred) }\CommentTok{#need to reverse the log to the real values}
\KeywordTok{head}\NormalTok{(predictions_lasso)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     1461     1462     1463     1464     1465     1466 
## 114351.8 162204.8 179455.3 197564.7 205952.8 169839.8
\end{verbatim}

\#\#XGBoost model

Initially, I just worked with the XGBoost package directly. The main
reason for this was that the package uses its own efficient
datastructure (xgb.DMatrix). The package also provides a cross
validation function. However, this CV function only determines the
optimal number of rounds, and does not support a full grid search of
hyperparameters.

Although caret does not seem to use the (fast) datastructure of the xgb
package, I eventually decided to do hyperparameter tuning with it
anyway, as it at least supports a full grid search. As far as I
understand it, the main parameters to tune to avoid overfitting are
max\_depth, and min\_child\_weight (see
\href{http://xgboost.readthedocs.io/en/latest/how_to/param_tuning.html}{XGBoost
documentation}). Below I am setting up a grid that tunes both these
parameters, and also the eta (learning rate).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xgb_grid =}\StringTok{ }\KeywordTok{expand.grid}\NormalTok{(}
\DataTypeTok{nrounds =} \DecValTok{1000}\NormalTok{,}
\DataTypeTok{eta =} \KeywordTok{c}\NormalTok{(}\FloatTok{0.1}\NormalTok{, }\FloatTok{0.05}\NormalTok{, }\FloatTok{0.01}\NormalTok{),}
\DataTypeTok{max_depth =} \KeywordTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{6}\NormalTok{),}
\DataTypeTok{gamma =} \DecValTok{0}\NormalTok{,}
\DataTypeTok{colsample_bytree=}\DecValTok{1}\NormalTok{,}
\DataTypeTok{min_child_weight=}\KeywordTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{ ,}\DecValTok{5}\NormalTok{),}
\DataTypeTok{subsample=}\DecValTok{1}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The next step is to let caret find the best hyperparameter values (using
5 fold cross validation).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#xgb_caret <- train(x=train1, y=all$SalePrice[!is.na(all$SalePrice)], method='xgbTree', trControl= my_control, tuneGrid=xgb_grid) }
\CommentTok{#xgb_caret$bestTune}
\end{Highlighting}
\end{Shaded}

As expected, this took quite a bit of time (locally). As I want to limit
the running time on Kaggle, I disabled the code, and am just continuing
with the results. According to caret, the `bestTune' parameters are:

\begin{itemize}
\tightlist
\item
  Max\_depth=3
\item
  eta=0.05
\item
  Min\_child\_weight=4
\end{itemize}

In the remainder of this section, I will continue to work with the
xgboost package directly. Below, I am starting with the preparation of
the data in the recommended format.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{label_train <-}\StringTok{ }\NormalTok{all}\OperatorTok{$}\NormalTok{SalePrice[}\OperatorTok{!}\KeywordTok{is.na}\NormalTok{(all}\OperatorTok{$}\NormalTok{SalePrice)]}

\CommentTok{# put our testing & training data into two seperates Dmatrixs objects}
\NormalTok{dtrain <-}\StringTok{ }\KeywordTok{xgb.DMatrix}\NormalTok{(}\DataTypeTok{data =} \KeywordTok{as.matrix}\NormalTok{(train1), }\DataTypeTok{label=}\NormalTok{ label_train)}
\NormalTok{dtest <-}\StringTok{ }\KeywordTok{xgb.DMatrix}\NormalTok{(}\DataTypeTok{data =} \KeywordTok{as.matrix}\NormalTok{(test1))}
\end{Highlighting}
\end{Shaded}

In addition, I am taking over the best tuned values from the caret cross
validation.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{default_param<-}\KeywordTok{list}\NormalTok{(}
        \DataTypeTok{objective =} \StringTok{"reg:linear"}\NormalTok{,}
        \DataTypeTok{booster =} \StringTok{"gbtree"}\NormalTok{,}
        \DataTypeTok{eta=}\FloatTok{0.05}\NormalTok{, }\CommentTok{#default = 0.3}
        \DataTypeTok{gamma=}\DecValTok{0}\NormalTok{,}
        \DataTypeTok{max_depth=}\DecValTok{3}\NormalTok{, }\CommentTok{#default=6}
        \DataTypeTok{min_child_weight=}\DecValTok{4}\NormalTok{, }\CommentTok{#default=1}
        \DataTypeTok{subsample=}\DecValTok{1}\NormalTok{,}
        \DataTypeTok{colsample_bytree=}\DecValTok{1}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The next step is to do cross validation to determine the best number of
rounds (for the given set of parameters).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{xgbcv <-}\StringTok{ }\KeywordTok{xgb.cv}\NormalTok{( }\DataTypeTok{params =}\NormalTok{ default_param, }\DataTypeTok{data =}\NormalTok{ dtrain, }\DataTypeTok{nrounds =} \DecValTok{500}\NormalTok{, }\DataTypeTok{nfold =} \DecValTok{5}\NormalTok{, }\DataTypeTok{showsd =}\NormalTok{ T, }\DataTypeTok{stratified =}\NormalTok{ T, }\DataTypeTok{print_every_n =} \DecValTok{40}\NormalTok{, }\DataTypeTok{early_stopping_rounds =} \DecValTok{10}\NormalTok{, }\DataTypeTok{maximize =}\NormalTok{ F)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1]  train-rmse:10.955588+0.004476   test-rmse:10.955537+0.019106 
## Multiple eval metrics are present. Will use test_rmse for early stopping.
## Will train until test_rmse hasn't improved in 10 rounds.
## 
## [41] train-rmse:1.428274+0.000561    test-rmse:1.428515+0.011791 
## [81] train-rmse:0.219833+0.000801    test-rmse:0.230612+0.009490 
## [121]    train-rmse:0.102497+0.001285    test-rmse:0.128856+0.008654 
## [161]    train-rmse:0.090461+0.001218    test-rmse:0.122128+0.007505 
## [201]    train-rmse:0.084142+0.001214    test-rmse:0.119557+0.007344 
## [241]    train-rmse:0.079398+0.001195    test-rmse:0.118374+0.007088 
## [281]    train-rmse:0.075716+0.001302    test-rmse:0.117645+0.006772 
## [321]    train-rmse:0.072567+0.001139    test-rmse:0.117136+0.006720 
## [361]    train-rmse:0.069770+0.001156    test-rmse:0.116745+0.006603 
## [401]    train-rmse:0.067201+0.001059    test-rmse:0.116505+0.006574 
## [441]    train-rmse:0.064814+0.001145    test-rmse:0.116386+0.006366 
## Stopping. Best iteration:
## [454]    train-rmse:0.063958+0.001067    test-rmse:0.116289+0.006326
\end{verbatim}

Although it was a bit of work, the hyperparameter tuning definitly paid
of, as the cross validated RMSE inproved considerably (from 0.1225
without the caret tuning, to 0.1162 in this version)!

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#train the model using the best iteration found by cross validation}
\NormalTok{xgb_mod <-}\StringTok{ }\KeywordTok{xgb.train}\NormalTok{(}\DataTypeTok{data =}\NormalTok{ dtrain, }\DataTypeTok{params=}\NormalTok{default_param, }\DataTypeTok{nrounds =} \DecValTok{454}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{XGBpred <-}\StringTok{ }\KeywordTok{predict}\NormalTok{(xgb_mod, dtest)}
\NormalTok{predictions_XGB <-}\StringTok{ }\KeywordTok{exp}\NormalTok{(XGBpred) }\CommentTok{#need to reverse the log to the real values}
\KeywordTok{head}\NormalTok{(predictions_XGB)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 116386.8 162307.3 186494.0 187440.4 187258.3 166241.4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#view variable importance plot}
\KeywordTok{library}\NormalTok{(Ckmeans}\FloatTok{.1}\NormalTok{d.dp) }\CommentTok{#required for ggplot clustering}
\NormalTok{mat <-}\StringTok{ }\KeywordTok{xgb.importance}\NormalTok{ (}\DataTypeTok{feature_names =} \KeywordTok{colnames}\NormalTok{(train1),}\DataTypeTok{model =}\NormalTok{ xgb_mod)}
\KeywordTok{xgb.ggplot.importance}\NormalTok{(}\DataTypeTok{importance_matrix =}\NormalTok{ mat[}\DecValTok{1}\OperatorTok{:}\DecValTok{20}\NormalTok{], }\DataTypeTok{rel_to_first =} \OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics[width=1\linewidth]{house-prices-lasso-xgboost-and-a-detailed-eda_files/figure-latex/unnamed-chunk-143-1}

\#\#Averaging predictions

Since the lasso and XGBoost algorithms are very different, averaging
predictions likely improves the scores. As the lasso model does better
regarding the cross validated RMSE score (0.1121 versus 0.1162), I am
weigting the lasso model double.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sub_avg <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\DataTypeTok{Id =}\NormalTok{ test_labels, }\DataTypeTok{SalePrice =}\NormalTok{ (predictions_XGB}\OperatorTok{+}\DecValTok{2}\OperatorTok{*}\NormalTok{predictions_lasso)}\OperatorTok{/}\DecValTok{3}\NormalTok{)}
\KeywordTok{head}\NormalTok{(sub_avg)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        Id SalePrice
## 1461 1461  115030.1
## 1462 1462  162238.9
## 1463 1463  181801.5
## 1464 1464  194189.9
## 1465 1465  199721.3
## 1466 1466  168640.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{write.csv}\NormalTok{(sub_avg, }\DataTypeTok{file =} \StringTok{'average.csv'}\NormalTok{, }\DataTypeTok{row.names =}\NormalTok{ F)}
\end{Highlighting}
\end{Shaded}


\end{document}
